### ISSUE TITLE
Make sure event loop timing is perfect to avoid tearing on platforms that don't support multi-buffering

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#105]
The tearing can be pretty savage on linux using X11 if drawing drifts out of sync due to the lack of support for multi-buffering. We could probably fix this by properly timing the event loop (rather than just sleeping for roughly the correct amount of time between intervals).

**Comment by mitchmindtree** [comment]
We should also track whether or not vsync is enabled as, if it is, we can avoid sleeping and doing our own timing at all. That said, I wonder if vsync will even be useful if we manage to do "perfect timing" in the first place.

**Comment by mitchmindtree** [comment]
To do this, we should add an example or test binary of some wort which prints all timing info to the screen at each frame so that we may test the *actual* timing using a high-speed camera. This info should include:

- Frame number.
- Ms since last frame drawn.
- Ms since start of application.
- Ms since update.
- The average frame rate over 100ms and over 1sec.

And whatever other info might be useful.

Perhaps there should be some GUI element that allows for adjusting the desired frame-rate and a toggle for whether or not the frame rate should be fixed.

**Comment by ivxvm** [comment]
@mitchmindtree
I'm not sure it's the same issue, but on windows any example with animation (like `simple_draw.rs` or `nature_of_code/chp_01_vectors/1_10_motion101_acceleration.rs`) is little bit laggy for me. Feels like there is a small lag every ~500ms.

**Comment by mitchmindtree** [comment]
Thanks for the heads-up @ivxvm! Yeah this sounds like it could certainly be related. Josh, Tom and I have been a little busy with another project over the past couple of months but it looks like we'll be getting the chance to get back onto nannou full time again very soon and this issue will be high on the priority list.

**Comment by mitchmindtree** [comment]
@ivxvm just letting you know that I should finish #208 within the next few days and I'm hoping it should address this!

**Comment by freesig** [comment]
Closing this as it should be fixed by vulkan. Reopen if not.
