### ISSUE TITLE
Add constrain, min() max() functions to primitive types

### ISSUE THREAD

**Issue by JoshuaBatty** [nannou-org/nannou#124]
Instead of having to define the minimum and maximum values to a clamp() function... It would be nice to just call min(val) to define a minimum value a variable can get to and likewise with a max(val) function.

**Comment by mitchmindtree** [comment]
There are already methods and functions for this provided in the std lib for the primitive types, e.g. `my_f32.min(other_f32)` returns the minimum value between the two. There's also `std::cmp::min` and `std::cmp::max` for integers.
