### ISSUE TITLE
Implement clamp() for Vector2 types.

### ISSUE THREAD

**Issue by JoshuaBatty** [nannou-org/nannou#125]
Currently clamp() doesn't work on Vector2 types which becomes an issue when working with Vectors in the Nature of Code examples.

**Comment by mitchmindtree** [comment]
In this case we want a `limit` function which "limit"s the magnitude of a vector which involves converting the vector to and from its magnitude - this is different from the regular `clamp` behaviour which directly clamps a value.

**Comment by mitchmindtree** [comment]
Closing in favour of #89.
