### ISSUE TITLE
Use nannou-specific Point and Vector types (rather than re-exporting cgmath types).

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#131]
Currently nannou exposes the `Point2`, `Point3`, `Vector2`, `Vector3`, etc types from cgmath. While these are well thought-out and map nicely to their associated mathematical models, we've noticed they might be a bit "complex" for nannou's goal of ultra-simplicity and new-user-friendliness. Some issues that we've run into:

- **Missing some high-level methods.** While porting the nature of code and generative gestaltung examples we have run into the desire for a number of higher level methods including:
    - `limit` or `clamp_magnitude`: clamps a vectors magnitude while retaining its angle. #125, #89.
    - `Vector2::angle`: produces the angle of the vector in radians. #126.
    - `impl From<Point2> for Vector2` and vice versa.
    - Operations (Mul, Add, Sub) on Points with Points. #107. Not 100% sure if we want this as it conflates the role of Point and Vector, but it seems to be a common bump for new users.
    - `set_magnitude` for Vectors while retaining angle.
    - A `normalise` method that returns `[0, 0]` when called on a `[0, 0]` rather than returning `[NaN, NaN]`.
- **Traits can be confusing for newcomers.** Many Vector and Point methods are provided via traits. While traits are nice for remaining generic, they require being imported into scope before their methods may be used. This is helped via the introduction of a prelude, however this is still a step that may confront new users earlier than necessary who may not understand why sometimes they can just call methods, and other times they have to add this seemingly unrelated `use foo::bar::*` line to the top of the prelude. If we were to add our own types, we could still implement the cgmath traits while also providing inherent implementations of each method that avoids the need for the user to import traits.
- **Reduce friction when wanting to add new methods/APIs.** While cgmath is thorough, nicely generic and maps well to the underlying mathematics, nannou prioritises simplicity for new users perhaps a little higher. As a result, it may simply be easier for us to maintain our own types in align with our own goals rather than negotiating API changes upstream. The tradeoff of course is that this means more initial work and maintenance work in nannou itself, and it also means potential improvements to cgmath would no longer make their way via nannou.
- **Default scalar values**. Nannou specifies a default "scalar" type that is used throughout the crate (geometry, graphics, etc). It would be nice if we could add this as the default scalar type parameter for the Point and Vector types.

Potential issues:

- Many libraries provide trait implementations for cgmath out of the box due to its pervasive use in the rust ecosystem. `glium` comes to mind as a crate that seems to provide out-of-the-box integration with cgmath (though it has been a while since I've checked and I could be wrong). We may lose this ease of integration if we switch to our own types which perhaps lack trait implementations already provided by other crates. We would at least still be able to implement the necessary traits ourselves, however we can't do much about APIs that expect specific cgmath point or vector types as their arguments without requiring a manual into/from conversion before/after each call. 
- We must ensure integration with other `cgmath` functionality. We may still want to take advantage of `cgmath` matrix/vector operations that perhaps use cgmath point and vector types as arguments or return types. A potential workaround would be to wrap all this functionality with our own types, which may require a lot of work but would at least remain a potential solution.

Not quite sure what direction to head in yet. cc @brendanzab would be great to get your thoughts if you get a chance, but no worries if you're busy! cc @JoshuaBatty.

**Comment by brendanzab** [comment]
I do want to at some stage have methods on the types themselves in cgmath. It would also be nice to have documentation that made it easier to get into using cgmath as well has a beginner, and then introduce the mathematical traits later as folks get a handle on the basics. Alas, as usual my head is stretched thin! Perhaps experimenting with your own wrappers would be a good start, but it would be neat if we could then figure out how to backport those learnings to cgmath itself! 🙂
