### ISSUE TITLE
Graphics use cases

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#15]
- [x] Render 2D Basic shapes
_Ellipse, Triangle, Line_
- [x] Clear frame with colour
- [x] Render text 
_Basic println! style with coordinates and width / height, wraps on newline_

**Comment by superdump** [comment]
I wrote some of these things for a 'learn some rust to build a processing-like rust lib' thing toward the end of last year. I'm not working on it now and perhaps won't continue but you're welcome to take a look at it, inspiration, code, etc. https://github.com/superdump/p5-rs However I did write using basic GL bindings as I wanted to also learn some GL.

There's also https://github.com/rennis250/processing-rs which uses glium I think so perhaps that is a better source. Also MIT licensed.

**Comment by mitchmindtree** [comment]
These have been implemented for a little while now, with efficient, cached text rendering ticking the last box in #484! While we still don't yet cover all the graphics use cases that we'd like to, missing cases might be better off as individual issues with the `graphics` label from this point onwards.
