### ISSUE TITLE
improvement: eventually switch passed parameters to random_range

### ISSUE THREAD

**Issue by transfluxus** [nannou-org/nannou#175]
make random_range check the first parameter is smaller then the second and swap then if not

**Comment by transfluxus** [comment]
not sure if  `rand.rs`, or to go somewhere deeper.

```
pub fn random_range<T>(min: T, max: T) -> T
where
    T: PartialOrd + distributions::range::SampleRange,
{
    if min <= max {
         rand::thread_rng().gen_range(min, max) }
    else {
        rand::thread_rng().gen_range(max, min) }
    }
}
```

**Comment by mitchmindtree** [comment]
Hey thanks @transfluxus! I actually just merged a PR for this about an hour ago at #176 :) I'm going to publish version 0.8.0 of nannou now with all the recent changes, this included!

**Comment by mitchmindtree** [comment]
This is the fix I used by the way - almost the same as what you just posted :+1: https://github.com/nannou-org/nannou/pull/176/files#diff-ac6cd28c911c8b1574249a44a9195374R37

**Comment by transfluxus** [comment]
In my experience `random_range` also crashes when min is equal to max!
