### ISSUE TITLE
simple_audio example does not work

### ISSUE THREAD

**Issue by BennetLeff** [nannou-org/nannou#189]
I've cloned and compiled the examples and found the simple_draw example which is shown in the project's README works. However, simple_audio (the example I'm most concerned with as I'm starting an audio application) doesn't do anything meaningful. It compiles and the executable runs but goes straight to a white blank screen which won't close unless I cancel the process in the terminal I run it from. 
Furthermore, I am definitely not getting any audio out! Perhaps the blank white screen is just a default, but I would expect it to be able to close it like other examples (by pressing the 'x'/window close button). Still, no audio indicates something more is wrong. I'm a bit new to Rust so forgive me if I'm missing something that should be obvious. I'm running Windows 10 with the Rust 1.28.0

**Comment by apiraino** [comment]
@BennetLeff it works for me, tested with latest (as we speak) Rust stable (1.27.2) and nightly (1.29) but I'm on Linux.

I confirm that the demo opens a window with gray background and plays a tone of 440 hz. The window can be closed clicking on the `X`, like you said.

I guess your Rust 1.28 is a nightly. Can you try again with the latest stable? I think in your case you should run:
```
$ rustup update
$ rustup install stable-msvc
```
([from the docs](https://github.com/rust-lang-nursery/rustup.rs#toolchain-specification))

**Comment by BennetLeff** [comment]
Now I've tried on my mac and I'm afraid I've created more problems than answers. Now I get an error on when I clone the repo and run cargo build. I've attached a picture to show the output but put succinctly, on Mac 10.13.6 with Rust 1.28, I get an error suggesting something's off with my coreaudio rust bindings.
![grab](https://user-images.githubusercontent.com/5445536/43692112-19f1853e-98ea-11e8-8b23-658af844c1e7.png)

**Comment by freesig** [comment]
Hey @BennetLeff can you try running it with `RUST_BACKTRACE=1 cargo build`

**Comment by JoshuaBatty** [comment]
@BennetLeff you need to remove Xcode command line tools and re-install them. This is due to Mac moving system headers around in 10.13 so system libraries like Core Audio aren't able to be linked otherwise.

**Comment by BennetLeff** [comment]
I will try those when I get back home tonight. 

I'm currently at work on a Windows 7 machine. I've tried cloning and running the audio example here and get the same (not working) behavior I've described. Perhaps it's a Windows bug? If anyone has quick/easy access to a Windows machine and can try cloning and running the audio example that would be great.

**Comment by BennetLeff** [comment]
Alright, I'm home and I've tried uninstalling and reinstalling the xcode command line tools per [these](https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_CAN_I_UNINSTALL_THE_COMMAND_LINE_TOOLS_) instructions (removing the files at `/Library/Developer/CommandLineTools`) and then running `xcode-select --install` but I still get the same errors as the screenshot I posted.

**Comment by freesig** [comment]
Just a thought but you mentioned you were running it from the git bash on the windows machine. I think you need to run it from something that has access to the visual studio environment variables. There should be a powershell installed (in the windows menu) called something like _vs-tools cmd tools_. You could try running it from that instead. I can get access to a windows machine later and will have a go.

As for the mac. Try running it with the Backtrace and putting the output on here. It might give a clearer picture of why it's failing.

**Comment by BennetLeff** [comment]
Alright, here's the Backtrace. Hope this helps 

![1](https://user-images.githubusercontent.com/5445536/43748462-50694aea-99b5-11e8-8197-91c3b5d3641c.png)
![2](https://user-images.githubusercontent.com/5445536/43748464-5224639c-99b5-11e8-9451-1051384418fc.png)

**Comment by freesig** [comment]
Yeh it looks like clang-sys is failing to find CoreAudio as @JoshuaBatty said. In the past reinstalling xcode tools has worked. I'll try and get the same macos version as you and see if I can replicate it.

**Comment by BennetLeff** [comment]
Thanks, I've posted on [StackOverflow](https://stackoverflow.com/questions/51737347/cargo-rustc-link-lib-cant-find-mac-frameworks-specifically-related-to-audio) to see if I can get a few more eyes on the problem. The behaviour seems almost unheard of anywhere on the net. In the spots I've found similar errors, the fixes we've tried have worked.

**Comment by freesig** [comment]
I'm going to close this issue but if you are still having trouble feel free to reopen.
