### ISSUE TITLE
OS cursor position does not match app.mouse

### ISSUE THREAD

**Issue by maxdee** [nannou-org/nannou#196]
My cursor position does not match the value of `app.mouse`, there seems to be a scaling issue.
With the default window size the printed cursor positions in each corner:

| left       | right           |
| ------------- | ------------- | 
| -512, 300 | 210, 300 |
| -512, -123 | 210, -123  | 

Running ubuntu 16.04
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 3.30
```
Could run a test on my e-gpu later :)

![alt text](https://imgur.com/DJltDqN.png)

```
extern crate nannou;

use nannou::prelude::*;

fn main() {
    nannou::view(view);
}

fn view(app: &App, frame: Frame) -> Frame {
    // Prepare to draw.
    let draw = app.draw();

    // Clear the background to pink.
    draw.background().color(LIGHT_PURPLE);

    // Draw a red ellipse with default size and position.
    // draw.ellipse().color(DARK_BLUE);
    println!("{}, {}", app.mouse.x, app.mouse.y);
    draw.ellipse()
        .x_y(app.mouse.x, app.mouse.y)
        .radius(4.0)
        .color(RED);

    // Write to the window frame.
    draw.to_frame(app, &frame).unwrap();

    // Return the drawn frame.
    frame
}
```

**Comment by mitchmindtree** [comment]
Thanks for the issue @maxdee!

Are you using X11 on Linux by any chance? If so, you might need to specify the `WINIT_HIDPI_FACTOR` environment variable to specify the correct scaling for your system. DPI on Linux is a tricky issue at the moment and I'm not sure if there is currently a reliable way to determine the correct scaling value on X11, so as a result the responsibility is currently on the dev to set this variable. I'd recommend reading [the winit DPI docs](https://docs.rs/winit/0.17.2/winit/dpi/index.html) to get a clear understanding of how DPI works on each platform (winit is the cross-platform windowing crate we use under the hood).

Let me know if this fixes things for you or if you're still running into issues!

**Comment by maxdee** [comment]
Setting the variable worked!
Is there a wiki or something where such info should be compiled?

**Comment by mitchmindtree** [comment]
Ultimately I'd like for us to work out a way to programatically determine this behind the scenes so that the user doesn't have to worry about this, e.g. maybe there's some config file or something we can look for if we're on linux and then set the env variable if it hasn't already been manually set by the user. I think that's a good point though - it's probably worth adding this to the README in the meantime, maybe under the platform-specific setup section.
