### ISSUE TITLE
Nannou Audio Device

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#199]
Currently there is no way to set which device you want to use as input and output. We have access to the Devices but the new_input_stream() and new_output_stream() 
## Solution
We could make those two functions take a Device. Then if the user just wants the default they can call default_input_device etc.

**Comment by mitchmindtree** [comment]
The [new_output_stream](https://docs.rs/nannou/0.8.0/nannou/app/struct.Audio.html#method.new_output_stream) method returns an output stream [Builder](https://docs.rs/nannou/0.8.0/nannou/audio/stream/output/struct.Builder.html) with which you can specify which [device](https://docs.rs/nannou/0.8.0/nannou/audio/stream/output/struct.Builder.html#method.device) you want to run that stream with (if you don't specify a device it uses the CPAL default). The input stream should work the same way. Is this what you're after?

**Comment by freesig** [comment]
Ah yep thats what I was after 👍
