### ISSUE TITLE
Exit fullscreen

### ISSUE THREAD

**Issue by floriama** [nannou-org/nannou#202]
On Linux, calling `window.set_fullscreen(...)` correctly puts the window into fullscreen mode.
However,  there doesn't seem to be a way to exit as no resizing operation has any effect.
`app.set_fullscreen_on_shortcut(true)` works fine, so there should be a way that exiting manually can be exposed to the user.

On another note, nice crate!

**Comment by mitchmindtree** [comment]
@floriama thanks for the issue!

Hmmm does it exit fullscreen if you call `window.set_fullscreen(None)` (rather than passing `Some(monitor_id)`)?

**Comment by floriama** [comment]
Ah yes that works. Maybe this should be documented, some people clearly don't figure it out on their own :)

**Comment by mitchmindtree** [comment]
Done! via #204.
