### ISSUE TITLE
Infinite loop find best matching format

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#205]
It's possible for nannou to enter an infinite loop when trying to find the best matching format.
1. It tries the supplied sample_format.
2. Then if no match is found the sample format is set to default
3. Then if default doesn't match go to step 2. (And loop forever)

Need a way to say we tried default and even that didn't work `Ok(None)`
Could do:
```rust 
if sample_format.is_some() {
  let last_try = sample_format.take();
  sample_format = default_format.as_ref().map(|fmt| fmt.data_type);
  if last_try == sample_format {
    return Ok(None);
  }
}
```
[This](https://github.com/nannou-org/nannou/blob/192bbd38061e1953a4d626afbdf60c9d815b7d6c/src/audio/stream/mod.rs#L352) is the function I'm talking about.

**Comment by mitchmindtree** [comment]
Yeah that sounds like a good approach to me :+1: Good spot!
