### ISSUE TITLE
Transition to Vulkan

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#208]
This is a follow up to #108 with some actionable steps!

The general plan is to depend on [vulkano](https://github.com/vulkano-rs/vulkano) for its type-safe API and switch out every that we currently use glium for it.

This [Vulkan Tutorial](https://github.com/bwasty/vulkan-tutorial-rs) should be a useful reference.

- [x] Run some example locally to verify that a few essentials currently work on stable:
    - Basic triangle.
    - GLSL to SPIR-V.
    - Textures (images).
- [x] Switch from using the glutin window and glcontext to vulkano-win.
- [x] Expose `vulkano::swapchain::Surface` methods from `Window`.
- [x] Add method for enumerating vulkan physical devices.
- [x] Add window builder that allows for specifying the physical device to use for the window's swapchain.
- [x] [Construct swapchain](https://vulkano.rs/guide/swapchain-creation) for window. Investigate whether this should be shared or unique between multiple windows.
- [x] Add `LoopMode` that only `update`s when the next image is ready for a specific window. ~Should consider making this a builder method on a window so that a unique update may be used for each if desired?~ Can't do this as i would require adding type params to the `App`.
- [x] Recreate `Frame` type using [`swapchain::acquire_next_image`](https://vulkano.rs/guide/acquire-present) future.
- [x] Get `LoopMode::RefreshSync` run loop working with a cleared image.
- [x] Add in swapchain recreation on resize.
- [x] Multi-window support.
- [x] Update other `LoopMode`s.
- [x] Recreate swapchains on `LoopMode` switch.
- [x] A window builder method that allows the user to construct the swapchain themselves.
- [x] Create vulkan based `draw` backend to replace the glium one. Refer to [triangle example](https://github.com/vulkano-rs/vulkano-examples/blob/master/src/bin/triangle.rs) for handling buffers.
- [x] Switch from using the glium backend of conrod to a vulkano one.

**Comment by mitchmindtree** [comment]
Some conditions that must be met:

- Allow for drawing to FBOs at any time.
- Allow for running compute shaders at any time.
- Restrict "swapchain" (window) drawing to the `view` function.

**Comment by mitchmindtree** [comment]
One big difference between OpenGL and Vulkan is that OpenGL sort of implicitly queues commands for the GPU behind the scenes, whereas Vulkan is very explicit about when the GPU is ready to process the next image.

Due to this OpenGL behaviour, Nannou's current behaviour is that when `view` is called the user is expected to draw to all windows at once and OpenGL would implicitly process the windows when it was ready. Vulkan on the other hand exposes the exact instant that each swapchain is ready to process the next image (via the `acquire_next_image` future) which raises the possibility that not all swapchains might be ready at the same instant, especially when windows are spread across multiple displays or driven by different physical GPUs.

## Changing the `view` function behaviour

Rather than expecting the user to draw to all windows at once within the `view` function, it could be a good idea to change the behaviour so that the user only draws to a single window each time `view` is called. The window for which `view` is called could be indicated via a `window_id` delivered with the `Frame` type. This would allow the `view` function to be called as *soon* as the swapchain for a window is ready to acquire the next image.

**Comment by mitchmindtree** [comment]
## The new Frame type

Seeing as the new `Frame` type would only contain the drawing context for a single window when it is ready for a new image, it will need the swapchain for that window and the current image that is ready to be acquired.

**Comment by mitchmindtree** [comment]
## Calls to `update` & The Swapchain.

I'm currently thinking a lot about how to best handle multiple windows with Vulkan.

Using Vulkan, each window must have its own `Swapchain`. The purpose of the swapchain is to synchronise the presentation of images with the refresh rate of the display.

In order to have the lowest possible latency, it would be useful to allow the user to specify a `LoopMode` that called `update` and then `view` each time vulkan indicates that the swapchain is ready to acquire a new image via `acquire_next_image`.

One issue that comes to mind is - how do we account for multiple windows in this case? I imagine most of the time multiple windows may be presented on the same physical device and display, meaning that the refresh rate would be the same and that the user probably only wants one call to `update` immediately before `view` is called for the first window to call `acquire_next_image`. One question that comes to mind is - how do you (and can you even) be sure whether the swapchains will be synchronised and which will be the first to request an image? However, we also have to consider the case where the user may have their windows spread across multiple different displays (e.g. a laptop display and one or more external monitors) - a case in which swapchains almost certainly will not be synchronised.

Do we call `update` once for each window? If so, does the user accept the case that `update` will be called at inconsistent intervals? E.g. if one display is 59.3hz and another is 90hz, the phase of the refresh rate will constantly be shifting over time, meaning sometimes there may be less than a millisecond between `update` calls, and sometimes a full 1/59.3 seconds. If this is considered OK, how do we determine when multiple swapchains' `acquire_next_image` calls will be synchronised and when they will not? Should we even bother trying to distinguish or should we just go for an `update` per window model?

Or perhaps instead only a single window's swapchain should drive the `update`s while the other swapchains simply present whatever the current state of the model happens to be when they are ready for their next respective images? If this option is worth considering, then perhaps it is worth considering not trying to synchronise with the `acquire_next_image` call whatsoever and instead looping at some self-timed rate (e.g. 60hz) and then let all the swapchains just present whatever the state is when `acquire_next_image` is ready? There are many options to consider. It would be nice to let the user choose this while also providing reasonable defaults.

## `LoopMode` Options

These are all the possible options that come to mind for `LoopMode`s as mentioned above:

- One `update` and one `view` for each call to `swapchain::acquire_next_image`.
- One `update` for each call to a single window's `swapchain::acquire_next_image` and a call to `view` for each window's `swapchain::acquire_next_image`.
- An arbitrary `update` rate specified by the user and a call to `view` for each window's `swapchain::acquire_next_image`.

Note that the `LoopMode::Wait` variant should not change as it is based on user input rather than display refresh rates. E.g. when some user input is received, `update` is called immediately and then `view` is called once for each display.

**Comment by freesig** [comment]
I don't fully understand this domain so my thoughts might be a bit misguided but I would imagine that you would not want to couple the update call to the refresh rate of the monitor. It would not be bad for example for a 90hz monitor to draw the same model twice if the scenario didn't have a reason to change the model.

I think it would be good to have a model that all monitors get in their acquire_next_image() and this model is updated by some master app loop with its own rate

**Comment by mitchmindtree** [comment]
> I would imagine that you would not want to couple the update call to the refresh rate of the monitor.

The reason I think it might be important to provide this option is in order to allow for minimizing latency as much as possible - that is the difference between the state that gets displayed and what the state actually should be at that exact instant. For example, if we have an arbitrary `update` rate of 60hz  but the display rate is 59.6hz or something, then the `update` latency will drift from from near-0 ms to about 16ms in a kind of saw wave pattern over time.

I think this generally gets really important for interactive applications or games where you want your view to seem as synchronised as possible with your actions. E.g. imagine the case where the `update` has drifted to the point where it occurs immediately after the swapchain retrieves the next image. Seeing as user input generally isn't processed into the application state properly until an application `update` is called, this means that any input that occurs between the drifted `update` call and the next `view` call will not actually be displayed until not the next `view` call but the one after that, meaning you can pretty easily get up to two whole frames (~32ms) of input latency.

> I think it would be good to have a model that all monitors get in their acquire_next_image() and this model is updated by some master app loop with its own rate

Just to clarify, `acquire_next_image()` is a function that is called per-swapchain and there is one swapchain per window. I don't actually know if it's possible to get the available monitor refresh rates at that point via vulkan or if the vulkan spec even guarantees that the window's swapchain will always exactly synchronise with whatever the rate of the monitor that the window happens to be on, I'm just assuming at the moment based on what I've read. It sounds like maybe what you're suggesting is similar to the idea of having one arbitrary `update` rate and then allowing each window to just present whatever the state is when their `acquire_next_image` function is ready. I think that's fine for some applications and we should definitely have a mode for that, but could become an issue for low-latency applications like mentioned above.

**Comment by freesig** [comment]
Ah I see what you mean. 
So what is the issue if they go out of sync? Is it that you are worried about them sharing the same model and one monitor might show the results of an event before another?

**Comment by freesig** [comment]
Like if one screen gets ahead of the other it will only get the latest available state of the model. 
I'm imagining that it's sort of like a pull system where events become available and then each screen pulls the events into their update loop. We would need to track which screen has already pulled an event and then once they have all received it then the event is consumed.
The same would be true for things that happen internally to your model. They would still be a type of event

**Comment by mitchmindtree** [comment]
> So what is the issue if they go out of sync?

I guess what I'm concerned about is, if you were to call `update` once for each swapchain's call to `acquire_next_image` and those swapchains were presenting at different rates, there would occasionally be moments where an `update` may get called twice (or more times) almost instantaneously on the occasions where those swapchains' calls to `acquire_next_image` all happen roughly at the same time. If that call to `update` was pretty expensive (like I imagine it could be for big applications) then each of the swapchains other than the one that happened to call `acquire_next_image` first would have to wait unnecessarily long for the `update` to be called again, even though they were all ready at roughly the same time and probably didn't need the extra `update` calls.

> I'm imagining that it's sort of like a pull system

Yeah true, maybe it should be possible to be able to specify a "minimum latency" interval in order to avoid this issue? That way when `acquire_next_image` is called, you could check if `update` has not been called at all within the last `minimum_latency_interval_duration` or if any user input has been received since the last `view` occurred and if either of those conditions are met then you know you have to call `update` before presenting to the swapchain, otherwise you can just use the existing state. Does that kind of make sense? If so, I wonder what the best way to offer this via `LoopMode` would be.

**Comment by freesig** [comment]
I was more imagining that each screen would be "subscribed" to the parts of the model that are relevant to it. Some of those parts would be shared among other screens. Each screen has it's own update that pulls in the relevant events and updates the model that it holds. Not calling one master update twice.
But yeh that could still involve duplicating work.

Or could it be more that an events are only applied once and the model is shared like
```
event1 on queue
screen1 calls update and this applies event1 to the model
screen2 calls update gets model with event1 already applied
screen2 calls no events, same model
event2 on queue
event3 on queue
screen2 calls update and events are applied, updated model is delivered
event4 on queue
screen1 calls update and gets model with all previous events applied plus event4 applied
screen2 gets same model that screen1 just got
```
I mean events in a sense more then UI events. Like you might have your physics engine sending movement events at a certain rate

**Comment by mitchmindtree** [comment]
Ok I think I get what you're saying by grouping all input and application events into a single "event".

To clarify, the reason why I am singling out user input events in particular is that those are the events that affect the feeling of "responsiveness" and low-latency to the user, as it is the point at which the user interacts with the system. The other distinction that I think is important is between events that occur from the external world (via I/O like user input, cam input, audio I/O, clocks, etc) vs events like physics updates that are generated within the application itself that the user has more control over. I'm generally lumping all the application events (physics etc) into the `update` function process as nannou itself can't really know exactly what application events the user might want to generate (e.g. a "todo" item was created, a pose occurred via skeleton tracking, a collision occurred, etc).

I do like the idea of allowing for an `update` per-window though. Perhaps similarly to allowing each window to have its own `view` function via a builder method on the `app.new_window()` call, we could also allow for passing an `update` function via a builder method which was called immediately when that window's swapchain's `acquire_next_image` function is ready? That way we don't have to try and add new `LoopMode`s for syncing with the swapchain - instead it's kind of implied that this is what you want if you pass an update function when building the window. Hmmmmmmmmm

**Comment by mitchmindtree** [comment]
For anyone else following along, this is the new `LoopMode` enum I'm thinking of going with following all this discussion. The main difference with the existing one is the addition of the `RefreshSync` variant.

```rust
/// The mode in which the **App** is currently running the event loop and emitting `Update` events.
#[derive(Clone, Debug, PartialEq)]
pub enum LoopMode {
    /// Specifies that the application is continuously looping at a consistent rate.
    ///
    /// An application running in the **Rate** loop mode will behave as follows:
    ///
    /// 1. Poll for and collect all pending user input. `event` is then called with all application
    ///    events that have occurred.
    ///
    /// 2. `event` is called with an `Update` event.
    ///
    /// 3. Check the time and sleep for the remainder of the `update_interval` then go to 1.
    ///
    /// `view` is called at an arbitraty rate by the vulkan swapchain for each window. It uses
    /// whatever the state of the user's model happens to be at that moment in time.
    Rate {
        /// The minimum interval between emitted updates.
        update_interval: Duration,
    },

    /// Waits for user input events to occur before calling `event` with an `Update` event.
    ///
    /// This is particularly useful for low-energy GUIs that only need to update when some sort of
    /// input has occurred. The benefit of using this mode is that you don't waste CPU cycles
    /// looping or updating when you know nothing is changing in your model or view.
    Wait {
        /// The number of `update`s (and in turn `view` calls per window) that should occur since
        /// the application last received a non-`Update` event.
        updates_following_event: usize,
        /// The minimum interval between emitted updates.
        update_interval: Duration,
    },

    /// Synchronises `Update` events with requests for a new image by the swapchain for each
    /// window in order to achieve minimal latency between the state of the model and what is
    /// displayed on screen. This mode should be particularly useful for interactive applications
    /// and games where minimal latency between user input and the display image is essential.
    ///
    /// The result of using this loop mode is similar to using vsync in traditional applications.
    /// E.g. if you have one window running on a monitor with a 60hz refresh rate, your update will
    /// get called at a fairly consistent interval that is close to 60 times per second.
    ///
    /// It is worth noting that, in the case that you have more than one window and they are
    /// situated on different displays with different refresh rates, `update` will almost certainly
    /// not be called at a consistent interval. Instead, it will be called as often as necessary -
    /// if it has been longer than `minimum_latency_interval` or if some user input was received
    /// since the last `Update`. That said, each `Update` event contains the duration since the
    /// last `Update` occurred, so as long as all time-based state (like animations or physics
    /// simulations) are driven by this, the `update` interval consistency should not cause issues.
    ///
    /// ### The Swapchain
    ///
    /// The purpose of the swapchain for each window is to synchronise the presentation of images
    /// (calls to `view` in nannou) with the refresh rate of the screen. *You can learn more about
    /// the swap chain
    /// [here](https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain).*
    RefreshSync {
        /// The minimum amount of latency that is allowed to occur between the moment at which
        /// `event` was last called with an `Update` and the moment at which `view` is called by
        /// a window's swapchain.
        minimum_latency_interval: Duration,
        /// The windows to which `Update` events should be synchronised.
        ///
        /// If this is `Some`, an `Update` will only occur for those windows that are contained
        /// within this set. This is particularly useful if you only want to synchronise your
        /// updates with one or more "main" windows and you don't mind so much about the latency
        /// for the rest.
        ///
        /// If this is `None` (the default case), `Update` events will be synchronised with *all*
        /// windows.
        windows: Option<HashSet<window::Id>>,
    },
}
```

**Comment by JoshuaBatty** [comment]
This is some epic work mitch maestro! Getting excited for all this Vulkan goodness.

**Comment by mitchmindtree** [comment]
## Main-thread Image Selection

The previously mentioned issues with selecting the next image to process on the main thread are:

1. How to avoid continuously looping without over-sleeping when checking each swapchain if it's ready to acquire the next image?
2. How to ensure that all swapchains have equal priority?

### Possible solutions

1. Use the `minimum_latency_interval` (or the interval /2) as a `sleep` duration if we check all swapchains and none of them are ready? The `minimum_latency_interval` implies that is the minimum acceptable time to wait, so maybe it's OK if we oversleep by an amount that is within that interval? It is not ideal timing, but possibly acceptable within the API?
2. Maybe it's OK to prioritise windows in the order in which they are created? In many cases, I imagine that swapchain images may become ready all at once (particularly if shown on the same device on the same display) and it may be useful for them to update in order.

   Perhaps the order does not matter at all, as long as after one swapchain becomes ready and its image is processed, all *other* swapchain images are checked directly after one at a time before beginning the loop again?

## Does syncing with refresh rate *require* blocking?

All that said, I just realised that although we can now avoid blocking on `swapchain::acquire_next_image`, I'm not certain that we won't have to block somewhere else if we want to synchronise with the swapchain refresh rate. E.g. It may turn out we will have to block on the drop that occurs when re-assigning the previous frame's future ([as mentioned here](https://github.com/vulkano-rs/vulkano/issues/1110#issuecomment-437909941)).

**Comment by mitchmindtree** [comment]
## The meaning of `LoopMode::RefreshSync`

`RefreshSync` is a `LoopMode` that describes synchronising input processing and updating the user model with the rate of the display refresh rate. From my understanding, the most suited (and reliably available) vulkan present mode for this is the FIFO mode with two images (a double-buffer). In this mode, the swapchain presents one image while allowing the user to write to the other image. The swapchain swaps these images when the display is ready for a new image. I'm assuming that on a 60hz display, this will happen 60 times per second.

More specifically to nannou - `RefreshSync` describes a loop mode in which we want to do each of these steps at the exact moment a new image is presented to the display.

1. Acquire the "free" image via `swapchain::acquire_next_image`.
2. Process application input.
3. Update the user model.
4. Submit a command to the GPU for drawing to the swapchain image and then present the image.

**Comment by mitchmindtree** [comment]
Ok, think I've got most of the system laid out now! Currently just trying to start with a basic `clear` call on the frame before getting into the graphics pipeline for the `draw` module.

Currently attempting to clear the frame via `clear_color_image` fails due to the swapchain image having an incompatible image layout. The error specifies that the image layout that fails is `PresentSrc`, whereas it seems we need the image to be in either `General` or `TransferDstOptimal`.

- Docs on [image layouts](https://vulkan.lunarg.com/doc/view/1.0.33.0/linux/vkspec.chunked/ch11s04.html).
- Docs on [clear color image command](https://vulkan.lunarg.com/doc/view/1.0.33.0/linux/vkspec.chunked/ch17s01.html).

**Comment by mitchmindtree** [comment]
It's been a long journey, but all these boxes are ticked! There are still a few small bug fixes and some macos build automation to land but they are mostly upstream issues. Otherwise, v0.9 should be just about Vulkan ready!
