### ISSUE TITLE
Add an example demonstrating how to create multiple windows that share a single graphics "context"

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#210]
This can be really useful for things like multi-screen displays, VJ software, etc.

There's a short discussion on this [here](https://github.com/SaschaWillems/Vulkan/issues/142).

**Comment by mitchmindtree** [comment]
This might be best as a `vk_multi_window.rs` example, that shows how to use the `Draw` API to draw to one large `Fbo` the size of two or three windows combined and then draw each section of that `Fbo` to each of the windows.

**Comment by JoshuaBatty** [comment]
I'm happy to make a `vk_multi_window.rs` example.

**Comment by mitchmindtree** [comment]
This is the default behaviour as of #452!
