### ISSUE TITLE
FBO API

### ISSUE THREAD

**Issue by JoshuaBatty** [nannou-org/nannou#214]
Wanted to jot down some ideas on the frame buffer API and some use cases in Nannou. 

A frame buffer is a pretty simple concept and used all the time in modern graphics programming, so it would be great to create a really easy to instantiate and use API around it. 

Below outlines the functionality that I have used framebuffers in the past for. 

**1. Allocate** 
This step should create a new FBO in memory and should at a minimum define the width and height of the object. Also, there should be optional builder methods for defining:
- ColorFormat -> RGB, RGBA, RGBAF32, ([Here](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml) are a bunch of GL colour formats)
- Number of Samples (used for MSAA)
- Number of Render Layers (the number of render targets associated with the FBO)
- Depth Image (should the FBO also contain a depth buffer)
- Stencil Image (should the FBO contain a stencil buffer)  

**2. Draw Something Into the FBO**
I'm imaging this will need some sort of `begin()` and `end()` calls. For example call fbo.begin() and then draw the contents of a fragment shader onto the fbo, then call end() after the frag shader is finished. 

During this stage we also need a way of clearing the currently stored memory in the FBO to an RGBA colour. This is especially needed for doing alpha trail like effects, and also when you are doing ping pong buffering. For example sometimes a shader will work on the Green channel but not the Blue and Red channels so it's important for clear the FBO to Green before each update pass for the effect to work. 

**3. Draw the FBO** 
Pretty straight forward just drawing the FBO onto a window. I'm imagining this will inherit all of the geometry draw builder methods, like x_y(). w_h(), rotation() etc.... 
If there is only a single render layer then calling fbo.draw() should present that, otherwise there should be a way of specify which render layer you want to draw. 

Similarly there should also be methods for draw_stencil() and draw_depth().  

**4. Get a reference to the FBO's texture**
This is used a lot when passing a texture into a shader. You want to just pass a reference to the memory location of the FBO on the GPU for the shader to use. Just like above, should have optional way of retrieving which render layers texture you want, or if you want the stencil of depth textures. 

**5. Loading Data directly into the FBO**
This is useful when using the texture data from a FBO in a shader to drive variables. For example, lets say you want to define the starting XY positions for a particle system shader. You should be able to store the X position in the Red channel and Y position in the Green channel. Each pixel in the FBO would be associated with a different particle. You can then store the velocity in the Blue channel. This is just a single example use case obviously. Below is a screen shot of an FBO using this type of system with particle system shader.
<img width="193" alt="screen shot 2018-11-22 at 11 32 29" src="https://user-images.githubusercontent.com/1289413/48881944-83bd1e00-ee4a-11e8-8206-d10ab5780796.png">

That's all I can think of for now. @mitchmindtree @freesig ...... Am I missing anything here?

**Comment by MacTuitui** [comment]
If the fbo (or maybe a more general image/texture class) could actually implement the draw api that would be ace. Like you would specify the render target of whatever draw command is queued but the api is the same. 
One specific use case I have in mind is to generate textures with the same calls you would use to create the final stuff, but just use that image/texture in the final comp.
I've been spoiled by the processing api that casually allows this but this might be too much to adapt here, especially with the switch to vulkan at the same time.

**Comment by mitchmindtree** [comment]
Yeah absolutely agreed! The current plan is to allow you to draw to a
framebuffer the same way you can currently draw to the Frame with a sort of
unified API. So for example you could do either `draw.to_frame(frame)` or
`draw.to_frame(my_framebuffer)`. This shouldn't be too tricky as we already
draw to a vulkan framebuffer under the hood when we draw to the Frame in
the existing API.

**Comment by mitchmindtree** [comment]
Closed by #272.
