### ISSUE TITLE
ResetFences

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#217]
So `acquire_next_image` calls vkResetFences.
So does v`view_frame`.
I think what might be happening is the view frame command buffer sometimes isn't finished by the time `acquire_next_image` is called.
But as per the spec https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkResetFences.html

> Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue

**Comment by freesig** [comment]
In all of Saschas vulkan examples he always calls `vkResetFences` like this
```C++
VK_CHECK_RESULT(vkWaitForFences(device, 1, &singleCB.waitFence, VK_TRUE, UINT64_MAX));
VK_CHECK_RESULT(vkResetFences(device, 1, &singleCB.waitFence));
```

**Comment by freesig** [comment]
Which example did you copy? I'll try and run it with debug and see if I get the same errors?

**Comment by mitchmindtree** [comment]
Just the vulkano-examples triangle example I think

**Comment by freesig** [comment]
Yeh it gives the fences error heaps.
Also noticed that the only calls to vkWaitForFences are with a timeout of 0. So it's never actually waiting on any fence. I'm not sure if this is something todo with how futures work though

**Comment by freesig** [comment]
relevant https://github.com/vulkano-rs/vulkano/issues/1065

**Comment by freesig** [comment]
This is the tracking issue https://github.com/vulkano-rs/vulkano/issues/1135 at vulkano.
I think we need to solve this before 0.9 can land. I'm going to do some more research and see if I can find a solution.

**Comment by freesig** [comment]
I think this could be a false positive.
