### ISSUE TITLE
Add intermediary image for `Frame` between user graphics and the swapchain images.

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#224]
Currently the `Frame` only exposes an option for writing directly to the images associated with the swapchain. This means that users who aren't using the provided `Draw` or `Ui` APIs currently have to setup a `Framebuffer` per swapchain image. This is a PITA, especially considering  these `Framebuffer`s need to be rebuilt every time the swapchain is rebuilt.

It would be nice to provide an optional intermediary image with the `Frame`  type that would allow users to only have to create a `Framebuffer` for this single image. A render pass would then be added after the `view` call ends that writes this intermediary image to whatever swapchain image is currently ready.

Further, we could also allow for an optional default render pass and framebuffer for this intermediary image and create an API that allows the user to only have to submit a `Subpass`, rather than construct the entire `RenderPass` and `Framebuffer` themselves.

Having each of these convenience layers be optional is essential in order to allow for hardcore uses to still have access to the lowest level they could possibly require.

**Comment by JoshuaBatty** [comment]
Yep this would be great, it's way too verbose otherwise and probably will scare people away from venturing outside of using just the `Draw` or `Ui` APIs.

**Comment by mitchmindtree** [comment]
#231 is a big step towards this but still a long way to go yet.

**Comment by mitchmindtree** [comment]
I think this will also make adding an API for reading and saving rendered frames to images way easier too, as we won't have to work out what swapchain image was the last one to be drawn and wait for it to finish being presented on the swapchain etc.

**Comment by mitchmindtree** [comment]
I'm currently looking into tackling this now!

I want to make sure we can still offer the current behaviour as there is a couple of potential benefits by working directly with the swapchain images including the ability to prepare multiple frames in parallel (useful for video players) and avoiding the cost of writing to the intermediary buffer on performance constrained systems (e.g. software render vulkan backends).

## Approaches

**Frame / RawFrame**

One option might be to allow the user to specify either a `RawFrame` or a `Frame` for the 3rd argument to their `view` function, where `RawFrame` gives the current behaviour of "raw" access directly to the swapchain image that will be drawn to for this frame while `Frame` will use the much friendlier intermediary image approach.

**"Lazy" Intermediate Image**

Another option is to just keep the single `Frame` type but then have the intermediary image only be created if it is actually used by the user. This might be a bit tricky in the sense that we would have to keep track of all possible ways in which the intermediary image might be accessed and check that it exists in each of these calls. When `view` is finished we would also have to have some way of dynamically deterring whether we need to draw the intermediary image to the swapchain image before submitting it for presentation or not.

I'm currently leaning towards the **Frame / RawFrame** approach as we can move most of this decision making and checking to compile time. This does have the side-effect of not being able to switch between drawing to the intermediary image or swapchain image at runtime, but I don't think it's unreasonable to require that someone just uses the `RawFrame` for everything if they need it at all and make their own intermediary image if they require one sometimes.

## MSAA

One interesting property of using an intermediary image is that we can use a multisampled image and let nannou take care of the render pass that resolves the intermediary msaa image to the swapchain image. Something worth considering then is how we allow users to specify the number of samples to use - currently we don't have to offer this as an option as we know the swapchain image can not be multi-sampled anyway.

One approach might be to add it as a builder method to the window, to ensure that each window frame can use a unique number of samples. One issue that comes to mind with this is that this builder method might be confusing for users who are using the `RawFrame` API. They might expect that specifying the number of samples indicates the number of samples in the swapchain image, whereas in reality this cannot be the case. A possible workaround might be to simply document the behaviour of the msaa samples builder and explain that we will `panic!` otherwise. Then at runtime during the `WindowBuilder::build` method, we could check both the `msaa_samples` parameter and the given `view` function and `panic!` if `msaa_samples` is `Some` and the `view` function expects a `RawFrame` with some useful message on why this doesn't make sense.

---

After all this is setup and working nicely I'll start thinking on how we can expose a nice way of rendering the `Ui` or `Draw` APIs to this intermediary image in a single renderpass by exposing a nice subpass API and a way of dynamically creating renderpasses (something vulkano doesn't currently provide). I have a `dynamic_renderpass` branch up but it's still a WIP.

**Comment by freesig** [comment]
One thing I would like to do is go through this https://github.com/SaschaWillems/Vulkan/blob/master/examples/offscreen/offscreen.cpp and compare it to the warp example I made. It should be a good way to make sure everything is setup correctly.

**Comment by mitchmindtree** [comment]
Closed via #242.
