### ISSUE TITLE
moltenvk_deps integration

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#233]
The moltenvk and env_perm crates are published now:
https://crates.io/crates/env_perm
https://crates.io/crates/moltenvk_deps

It's probably a good idea to do a quick review of the code but I think it's all good.
How should we include this into Nannou?
I'm thinking a build.rs just for mac that checks or installs the dependencies through the crate?

**Comment by mitchmindtree** [comment]
I think the best approach would be to try and land this in vulkano's build.rs behind a feature like [discussed here](https://github.com/vulkano-rs/vulkano/issues/927).

While it would probably be easier for us to merge it and maintain in nannou, we can't really do it from a build.rs in nannou, as vulkano is an upstream dep and cargo will always try and compile vulkano before even running the nannou build script.

It could be worth adding it to the vulkano build.rs then doing a PR to first get some feedback, and then once everyone is happy with how it looks do a call-out for mac users to try it to see if it makes vulkano "just work" for them as expected.

**Comment by freesig** [comment]
Yeh ok good call, I'll try that now

**Comment by freesig** [comment]
This is blocked because we have no way to set environment variables from a child process.
When the deps and env vars are set the build finishes but the env vars are not set in the environment that the user (cargo) runs the binary from.
The env vars are needed to dynamically link to the vulkan and molten libraries.

This can be solved by sourcing .profile or restarting terminal.
However I have not found any way to automate this so far.

**Comment by freesig** [comment]
One idea might to be actually put code in Nannou that is under a macos cfg.
It could just check if the env vars are visible and then set them.
Could also do this in Vulkano but that might not be something they want.

**Comment by mitchmindtree** [comment]
> put code in Nannou that is under a macos cfg

@freesig by this do you mean having some macos cfg in something very early in the nannou initialisation process that checks for the env vars and sets them if they're not already set? This does sound like it would work, but I wonder where the best place to put it would be. The app builder is the first entry point of the nannou program, but even the builder can take some vulkan arguments via builder methods, like a custom vulkan instance, or a vulkan debug callback, so I imagine the env vars may be necessary in come cases before any nannou setup begins.

It would be very useful to know exactly where those env vars are first used, but it might be tricky to work out as the `VULKAN_SDK` is prepended to the `PATH` and `DYLIB_LIBRARY_PATH`, so we'd probably need to know whatever binary/shared lib is being accessed from it to find where it's being used in molten code.

I just noticed this under the env var section of the vulkano readme:

> It is also possible to link with the MoltenVK framework (as vulkano did in previous versions) by adding the appropriate cargo output lines to your build script and implementing your own `vulkano::instance::loader::Loader` that calls the MoltenVK `vkGetInstanceProcAddr` implementation.

Maybe if we can't work out a nice solution with the env vars we can suss out what's involved in doing this and whether it might give us the control we need? I guess there's probably a reason vulkano bailed on this though, might be worth finding that PR.

**Comment by freesig** [comment]
I think we face the same issue though even if we were to implement an instance::Loader. 
We need to know where MoltenVK / VulkanSDK is installed.
If we decided that it could only be installed in one location. ie `$HOME/.vulkan_sdk` then we wouldn't need the env vars because we could just hard code the paths.

I think the loader get's called when you make an instance but we need some way to pass the path to vulkansdk from meteln_deps to nannou otherwise we can't set them anyway. I'll have a look into this now.

**Comment by freesig** [comment]
I found a flag in cargo that lets you set an env var from a build script but it only works if you are using the crate directly.
It doesn't work if you are building from a something that uses it as a dependency :(

**Comment by freesig** [comment]
Ok I'm going to try and implement this from nannou with a few minor changes in vulkano.

**Comment by freesig** [comment]
@mitchmindtree You mentioned before you're not sure the best place to put this because one day you might want to have the option to compile without a window. Wouldn't the `App Builder` still be used though?

**Comment by freesig** [comment]
I think the only places a builder can be created are in the `Builder::new()` and `Builder::sketch()` so these are probably a good place to check if vulkano deps are installed

**Comment by freesig** [comment]
Ok this works from if I call it from those methods
