### ISSUE TITLE
Polygon and convexity?

### ISSUE THREAD

**Issue by MacTuitui** [nannou-org/nannou#245]
I'm trying to draw a polygon with the following code:

```rust
let mut points = Vec::new();
let s = 5;
for k in 0..s {
    let frac = (k as f32)/(s as f32);
    let angle = frac*TAU;
    let r = (frac-0.2).abs() * 300.0;
    points.push(pt2(r*angle.cos(), r*angle.sin()));
}
draw.polygon()
    .points(points)
    .rgba(1.0, 1.0, 1.0, 0.4);
```

<img width="231" alt="screen shot 2019-01-21 at 14 31 08" src="https://user-images.githubusercontent.com/1924395/51454673-3cd7a000-1d89-11e9-8912-0afc820bebea.png">

But it looks like the order of the vertices is changed somehow. I'm lost as to why (convexity? triangulation?).

**Comment by JoshuaBatty** [comment]
Thanks @MacTuitui . Can you provide a rough drawing of what shape you were intending?

**Comment by MacTuitui** [comment]
That would be the "darker" one.

**Comment by freesig** [comment]
Is the problem that there is 5 vertices?

**Comment by mitchmindtree** [comment]
Ah yep, the current polygon API doesn't allow for drawing concave shapes unfortunately! I'll open up an issue about adding support for concave polygons as it should totally be doable with the same API, we'll just need to do the triangulation differently behind the scenes.

Maybe in the meantime this could be better achieved using `draw.mesh()` for now?

**Comment by MacTuitui** [comment]
But it kind of does actually: 

````rust
    let mut points = Vec::new();
    let s = 5;
    let gfrac = 0.3;
    for k in 0..s {
        let frac = (k as f32)/(s as f32);
        let angle = frac*TAU+0.01;
        let r = (frac-0.6).abs() * 300.0;
        points.push(pt2(r*angle.cos(), r*angle.sin()));
    }
    draw.polygon()
        .points(points)
        .rgba(1.0, 1.0, 1.0, 0.4);
````

<img width="282" alt="screen shot 2019-01-21 at 14 38 21" src="https://user-images.githubusercontent.com/1924395/51454862-3eee2e80-1d8a-11e9-8252-64389f32c62d.png">

That's why I'm confused...

**Comment by mitchmindtree** [comment]
Yeah so the reason why it works sometimes is that the polygon triangulation is done by joining every following pair of vertices with the first vertex, so for example if the concave section occurs in line with the first point, the triangulated polygon will have a section that overlaps back over the top of the concave section when it joins the following points.

In case you're interested in where we need to do the actual fix, [here is the polygon triangulation iterator](https://github.com/nannou-org/nannou/blob/master/src/geom/polygon.rs#L130-L134). It's very simple at the moment, I'm sure it wouldn't be too tricky to fix but I don't know the concave support approach off the top of my head.

**Comment by MacTuitui** [comment]
It's pretty hard to be honest! 
FWIW, it looks like `processing` defaults to the GLU tessellation.

**Comment by mitchmindtree** [comment]
Ahh thanks for the heads up! I'll do some investigating in the future if no one beats me to it. I can image it would get especially tricky when you have overlapping shapes like stars.

It looks like there's a nice writeup [here](http://www.glprogramming.com/red/chapter11.html).
