### ISSUE TITLE
Blend modes

### ISSUE THREAD

**Issue by MacTuitui** [nannou-org/nannou#247]
I'm a pretty heavy user of blendModes in Processing, especially ADD/SUBTRACT and EXCLUSION.

Some typical use cases for me: 

- to get a slow fade-to-black blur effect: use SUBTRACT and draw a (255,255,255,1) filled rectangle
- to get a slow fade-to-white blur effect: use ADD and draw a (255,255,255,1) filled rectangle
- to get a nice cross effect on lines: use ADD and use very faint transparency -> the intersections will "pop up". 
- Cheapest trick in the book: use EXCLUSION and draw random moving shapes filled with WHITE -> you'll get all the combinations of the intersections of the shapes for free. Also nice as a finishing touch by drawing a big circle to frame the whole picture. 

I'd love to get a way to have access to these (or even write the blend function myself). I'm thinking something along the lines of ```draw.whatever().[...].color(WHITE).blend(MODE);``` might work but I haven't spent a lot of time to think on this. 

Internally I don't know what would be the cost of switching blendmode on each call, but I'm studying hard!

**Comment by scalarwaves** [comment]
It looks like processing-rs has an implementation of this: https://github.com/rennis250/processing-rs/blob/4fcee2b82f4a3d8dc88b9452086f7102e21c5fdd/src/rendering.rs

**Comment by mitchmindtree** [comment]
Support for blend modes in the `Draw` API has been added as of #484! See the `examples/draw/draw_blend.rs` example for a small demonstration. If any features in particular are missing, feel free to open a new issue. This work will be published as a part of the upcoming 0.14 release.
