### ISSUE TITLE
error: failed to run custom build command for `miniz-sys v0.1.11`

### ISSUE THREAD

**Issue by rileyjshaw** [nannou-org/nannou#254]
MacOS Mojave, 10.14.3 (18D42)

I encountered an error when running `cargo run` from `nannou-new/`:

```
error: failed to run custom build command for `miniz-sys v0.1.11`
process didn't exit successfully: `/Users/rileyshaw/code/nannou/nannou-new/target/debug/build/miniz-sys-fd44ee6f6dea9485/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-DMINIZ_NO_STDIO" "-DMINIZ_NO_ARCHIVE_APIS" "-DMINIZ_NO_ARCHIVE_WRITING_APIS" "-DMINIZ_NO_TIME" "-DMINIZ_NO_ZLIB_COMPATIBLE_NAMES" "-o" "/Users/rileyshaw/code/nannou/nannou-new/target/debug/build/miniz-sys-f30308b855b9e91c/out/miniz.o" "-c" "miniz.c"
exit code: 0
AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
running: "ar" "crs" "/Users/rileyshaw/code/nannou/nannou-new/target/debug/build/miniz-sys-f30308b855b9e91c/out/libminiz.a" "/Users/rileyshaw/code/nannou/nannou-new/target/debug/build/miniz-sys-f30308b855b9e91c/out/miniz.o"
cargo:warning=/opt/local/bin/ranlib: object: /Users/rileyshaw/code/nannou/nannou-new/target/debug/build/miniz-sys-f30308b855b9e91c/out/libminiz.a(miniz.o) malformed object (unknown load command 1)
cargo:warning=ar: internal ranlib command failed
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/Users/rileyshaw/code/nannou/nannou-new/target/debug/build/miniz-sys-f30308b855b9e91c/out/libminiz.a" "/Users/rileyshaw/code/nannou/nannou-new/target/debug/build/miniz-sys-f30308b855b9e91c/out/miniz.o" with args "ar" did not execute successfully (status code exit code: 1).

', /Users/rileyshaw/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.28/src/lib.rs:2314:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Really excited to use this framework. Thanks for all the work!

**Comment by mitchmindtree** [comment]
Ahh thanks a for the issue!

I'll have a look into what's going on with `nannou-new` next time I have access to a mac - it would be interesting to see what's using `miniz-sys` via `cargo tree`.

It might be useful to know that currently `nannou-new` doesn't do much other than automatically add the nannou dependency to your Cargo.toml and setup some template code (a copy of either of the `template_*.rs` examples) so in the meantime just using regular `cargo new` should be fine as a workaround.

**Comment by mitchmindtree** [comment]
Ahh it sounds like you might be running into an issue unrelated to nannou itself if you're also getting errors when installing `cargo-tree`.

What is the output of `rustc --version` and `cargo --version`? It might worth trying to update rust if possible - while newer versions of rustc are backwards compatible with older rust code, some upstream crates occasionally use some of the newer features breaking compatibility with older rustc versions.

**Comment by rileyjshaw** [comment]
```
~  ⋄ rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)
~  ⋄ cargo --version
cargo 1.32.0 (8610973aa 2019-01-02)
~  ⋄ rustup update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: checking for self-updates

  stable-x86_64-apple-darwin unchanged - rustc 1.32.0 (9fda7c223 2019-01-16)
```

I'm on the latest stable version as far as I can tell, but I can try updating to beta or nightly if you think that might be the cause?

**Comment by mitchmindtree** [comment]
Hi @rileyjshaw sorry about the delay! We've been busy with some downstream commercial work (using nannou!) and this slipped my mind, did you ever sort out your issue? Searching for `Internal error occurred: Command "ar" "crs"` (from the error you posted previously) seems to show quite a few results that might be handy.

I'm going to close this seeing as the problem doesn't seem to be related to nannou itself. Feel free to keep commenting here with your progress sorting it out if you like though!
