### ISSUE TITLE
Mac UnsupportedPresentMode

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#262]
This loop mode in the `simple_ui.rs` is not supported by MoltenVK
`app.set_loop_mode(LoopMode::wait(3));`
If I try and run it I get 
```
thread 'main' panicked at 'failed to recreate swapchain for new `LoopMode`: UnsupportedPresentMode'
```

Is there an alternative low energy mode?

**Comment by mitchmindtree** [comment]
@freesig are you able to run `vulkaninfo` on your mac? If so, can you paste the output here? There should be a section where it enumerates the available present modes that would be handy to see. Both the `Wait` and `Rate` nannou loop modes attempt to use the MAILBOX present mode, but it looks like this isn't available on macos.

The vulkan spec itself *does* mention that the only present mode that is always guaranteed to be supported by every swapchain implementation is the FIFO mode, I didn't realise just how many devices *only* support that mode. E.g. I think this linux desktop with the nvidia GPU also doesn't support MAILBOX.

We should be able to do a check and fallback to FIFO mode if MAILBOX isn't available. This should be fine for the `Wait` loop mode, but will limit the `Rate` loop mode to whatever rate at which `acquire_next_image` returns new images (but this is probably way better than crashing anyway).

**Comment by freesig** [comment]
Present Modes:
FIFO_KHR
IMMEDIATE_KHR
