### ISSUE TITLE
Setup travis to check `rustfmt` formatting

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#298]
Now that #297 landed maybe it's best to enforce correct formatting in commits and have travis produce an error if formatting is incorrect?

One alternative would be to instead setup travis to add a commit that applies `rustfmt` in the case that a PR is incorrectly formatted when merged into master, but maybe this might cause some odd git conflict issues if someone branches from a previously merged branch without realising that travis has added a commit on top of the original branch?

cc @freesig

**Comment by freesig** [comment]
I personally like the auto commit rustftm.
When I accidentally forget to trim white space and then need to re-wait for travis to compile on vulkano I want to cry lol

**Comment by mitchmindtree** [comment]
Yeah agreed, it would also take the burden off new contributors which is definitely something we want!
