### ISSUE TITLE
Segfault on resizing smaller

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#299]
All nannou applications are currently segfaulting when the window is resized to a smaller size.
It's probably something wrong with the the pipeline recreation.

**Comment by freesig** [comment]
I just realized that this is due to https://github.com/KhronosGroup/MoltenVK/issues/584

**Comment by mitchmindtree** [comment]
Ahh true, so this is still happening for you? Nice work on tracking down the issue!

**Comment by mitchmindtree** [comment]
Going to close this as the linked issue is also closed, but feel free to re-open if its still happening!
