### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#3]
One of the nicest things about working with OF or Processing is how easy it is to just instantly draw something to the screen. There's no worrying about triangulation, where vertices should be stored, caching, or anything like that - it's as simple as `ellipse(x, y, w, h)`, `ofRectangle(x, y, w, h)`, `text("stuff", x, y)`, etc.

The frustrating thing about these functions is that they're generally pretty inefficient, and when you do start running into performance bottlenecks you do have to start thinking about meshes and in turn nice ways of packing vertices, indices, etc.

It would be really nice if we could offer something that felt this nice to use, but cached all of these commands into a big buffer that gets drawn all in a single graphics call and gets re-used between frames for efficiency.

Imagining something along these lines:

```rust
fn draw(app: &App, model: &Model, frame: Frame) -> Frame {
    let ref mut g = app.graphics();

    // Building relative layout.
    let background = draw::background(model.window).color(color::RED).set(g);
    let ellipse = draw::ellipse().on(background).x_y_w_h(10.0, 20.0, 30.0, 40.0).set(g);
    let rectangle = draw::rectangle().wh_of(ellipse).down_from(ellipse, 10.0).set(g);
    draw::text("doot doot").middle_of(rectangle).set(g);

    // Shorthand for common stuff.
    g.clear(color::RED);
    g.ellipse(10.0, 20.0, 30.0, 40.0);
    g.rectangle(40.0, 30.0, 20.0, 10.0);
    g.text("doot doot");
    
    // Submit the graphics to OpenGL.
    g.draw_to_frame(&frame);

    frame
}
```

**Comment by mitchmindtree** [comment]
TODO
--------

- Add `geom` module for working with geometry. This will provide efficient primitive sources of vertices.
    - 1D primitive graphics
        - [x] range
    - 2D primitive graphics
        - [x] triangle
        - [x] quad
        - [x] rectangle
        - [x] line
        - [x] polyline
        - [x] ellipse
        - [x] polygon
        - [ ] arrow2d
    - 3D primitive graphics
        - [ ] cylinder
        - [ ] plane
        - [ ] sphere
        - [ ] cube
        - [ ] n-sided prisms
        - [ ] n-sided pyramids
        - [ ] cone
        - [ ] arrow3d
        - [ ] torus
        - [ ] n-sided hedron
- Add a graphics graph. For composing graphics primitives together with relative positioning, etc.
- Add `mesh` module for working with vertices, textures, normals etc.
- High-level `Graphics` API object as demonstrated in the previous comment.

**Comment by mitchmindtree** [comment]
Geometry Graph
---------------------

The idea behind the geometry graph (`geom::graph`) is to allow for composing together multiple primitives relative to one another and to other graphs.

`Node`s may be some `Primitive` geometry (e.g. triangle, sphere, cuboid) or other geometry `Graph`s.

`Edge`s describe the relative association between nodes. Users should be able to describe relative associations between nodes as `Position` (displacement), `Rotation` (relative orientation) and `Scale`.

The resulting position, orientation and scale of a node within the graph along each axis is specified as:

- **scale** = 1.0 * parent_scale * edge_scale
- **position** - 0.0 + parent_position + edge_displacement
- **orientation** - 0.0 + parent_orientation + edge_rotation

**Comment by mitchmindtree** [comment]
## Vertex Indices

In many cases it will be far more efficient to perform triangulation of geometry via indices into an existing vertex buffer, rather than storing every vertex required or yielding each vertex via an iterator. It would be useful to provide iterators yielding indices (or in some cases constant arrays) in order to take advantage of this.

- [x] **Tri::from_index_tri**
- [x] **Tri::from_indices**
- [x] **quad::TRIANGLE_INDEX_TRIS**
- [x] **quad::TRIANGLE_INDICES**
- [ ] **ellipse::triangle_index_tris** (from resolution)
- [ ] **ellipse::triangle_indices** (from resolution)
- [ ] **Ellipse::triangle_index_tris**
- [ ] **Ellipse::triangle_indices**
- [ ] **ellipse::Section::triangle_index_tris**
- [ ] **ellipse::Section::triangle_indices**
- [ ] **polygon::triangle_indices** (from vertex slice containing all polygon vertices)
- [ ] **polyline::triangle_indices** (from vertex slice containing all line ends)
- [ ] **cuboid::triangle_index_tris** (a trio of indices into the corners of the cuboid for each triangle)
- [ ] **cuboid::triangle_indices** (a trio of indices into the corners of the cuboid for each triangle)
- [ ] **Cuboid** methods for the above two.

**Comment by mitchmindtree** [comment]
## Draw API

The draw API is a high-level wrapper around drawing, colouring and texturing geometry in 3D space. A user can begin drawing in their **view** function like this:

```rust
fn view(app: &App, model: &Model, frame: Frame) -> Frame {
    let draw = app.draw();
    // Use `draw` to draw stuff here.
    draw.to_frame(&frame).unwrap();
    frame
}
```

Here's an example of drawing an ellipse:

```rust
draw.ellipse();
```
This draws an ellipse in the middle of the screen (`0, 0` aka the defualt position) with some default width, height and colour.

To specify the dimensions for the ellipse, we could do the following:

```rust
draw.ellipse()
    .w_h(100.0, 200.0);
```

Further, we might want to specify a position and colour:

```rust
draw.ellipse()
    .w_h(100.0, 200.0)
    .x_y(-300.0, 300.0)
    .color(color::PURPLE);
```

You, as a creative user should be able to use `draw` to express only what you feel like expressing. For example, above we start out knowing only that we want to draw an ellipse - we haven't yet thought about (nor do we care about) the position, dimensions, color, etc. By allowing us to simply specify `draw.ellipse()` with no other parameters, we're able to begin visualising immediately and start the artistic/creative feedback loop as quickly as possible. Once we're in this feedback loop we can start thinking about and expressing other properties as we think of them e.g. `.w_h(100.0, 200.0)`, `.color(color::PURPLE)`, etc.

## Implementation

When calling `draw.ellipse()` (or any other shape) a `Drawing` type is returned. The `Drawing` type can be used to chain methods specifying more properties about the shape, e.g. `.w_h(100.0, 200.0).color(color::PURPLE)`.

Only once this **Drawing** type is dropped does it actually submit the drawing to inner **Draw** geometry graph and mesh. In the case that some property was never specified (e.g. position or colour) a default, fallback value is used instead. These defaults can be customised using the **draw::Theme** type.

As the **Drop** order of bindings within a lexical scope is the *reverse* of the instantiation order, the **Draw** type have a way of maintaining ordering. This is done by returning an instantiation index within the returned **Drawing** each time drawing begins. This way when **Drop** is called, the **Drawing** can act based upon the instantiation order rather than the reversed drop order.

**Comment by freesig** [comment]
Nice work!
Just a thought on the graph. I wonder if it may be hard to reason about where something will end up because you will need to know its parents location and its parents parents etc.
Or will it be more that each "collection" of primitives will be in a graph?
ie. in a scene with a person, the ground and a house:
The primitives that make up the person, house and ground will all have their own tree graphs, all relative to the origin (0, 0, 0)
This would be like how glTranslate works where everything is a series of translations from the origin but expressed in an explicit tree graph. Where each child is relative to the parents "translation".
All siblings would be in the same "space".
If so I think this is a great idea because you don't need to mentally "track" all the translation calls in order to position something.

Sorry just trying to get my head around it :)

**Comment by mitchmindtree** [comment]
> Or will it be more that each "collection" of primitives will be in a graph?

@freesig yeah it should be possible to make a single graph as complex or as simple as you like! E.g. you could have one big graph describing the whole ground, house and person, or you could create a graph for each of these and then compose those together with another graph (graph's can be nodes in other graphs). Each graph always has at least one node (the **origin** node at 0,0,0) which acts as the "parent" node if a specific one is given. This way we can guarantee that every node is connected which makes it much easier and more efficient to do the DFS - in other words we don't have to calculate the strongy connnected components because it the whole graph is one big strongly connected component.

The graph currently provides a way of getting the **Transform** for every **Node** in depth-first-search order of discovery, with helper methods that use these transforms for getting iterators yielding all transformed vertices or triangles for each individual node or for the whole graph.

I'll also add methods for getting the transform for individual nodes (e.g. `graph.node_transform(nod_id)` or something like this) which doesn't require doing the full DFS and instead gets the node's transform by traversing only the parents of the node at `node_id`.

> If so I think this is a great idea because you don't need to mentally "track" all the translation calls in order to position something.

Yeah totally agreed! I always get confused trying ot look at gltranslate matrix transformations and remember what's going on. I think having the graph will also be nice in that we can reflect upon what's been built  e.g. we can easily refer to the position of some grandparent's grandparent using its `node::Index` or by using one of the graph's parent traversal methods. It should also be cool for doing cool effects over an entire graph, e.g. you could make some cool geometric rippling  effect by mutating node positions by feeding their x, y position into some sine/cosine combo.

> Sorry just trying to get my head around it :)

No worries man, glad you had a chance to have a look! Looking forward to getting some feedback from you and joshy on all this. Just trying to get it to a usable place before diving back into audio_server. Currently working on the **Draw** API which is basically a super high-level API around the geometry graph and mesh types :) Hoping to see a little nannou ellipse on the screen by the end of today / tomorrow!

**Comment by mitchmindtree** [comment]
Going to close this as the issue is old, overly general and we're well on the way with our graphics implementation as is.
