### ISSUE TITLE
DEPTH_FORMAT should not be const D16Unorm

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#303]
[This](https://github.com/nannou-org/nannou/blob/27464de0c359b3fcfc3c132343f468f6ac6296af/src/app.rs#L46) shouldn't be a const.
It needs to be verified that the host system actually supports the value. It should probably be selected from a list of supported formats from the host system.

**Comment by mitchmindtree** [comment]
OK so I had a go at implementing a proper solution to this following the vulkan tutorial [here](https://vulkan-tutorial.com/Depth_buffering#page_Depth-image-and-view).

In the `vk` module with the `vk-sys` crate imported as `sys`:

```rust
// Given a slice of candidate formats in order of preference, return the first that is supported.
fn find_supported_image_format(
    candidates: &[Format],
    physical_device: &PhysicalDevice,
    tiling: sys::ImageTiling,
    features: sys::FormatFeatureFlags,
) -> Option<Format> {
    // TODO: Apparantely the vulkan pointers are private?
    let vk_ptrs = physical_device.instance().pointers();
    let physical_device = physical_device.internal_object();
    for &format in candidates {
        let fmt = format as u32;
        // The `vulkano` crate currently does not provide a way to query supported image formats.
        // This unsafe block is used used to query the low-level `sys` bindings ourselves.
        unsafe {
            let mut props: sys::FormatProperties = std::mem::zeroed();
            vk_ptrs.GetPhysicalDeviceFormatProperties(physical_device, fmt, &mut props);
            if tiling == sys::IMAGE_TILING_LINEAR && (props.linearTilingFeatures & features) == features {
                return Some(format);
            } else if tiling == sys::IMAGE_TILING_OPTIMAL && (props.optimalTilingFeatures & features) == features {
                return Some(format);
            }
        }
    }
    None
}
```

This is pretty much a direct port, and would work if the `Instance::pointers` method was not private. I'm going to leave this attempt here for future reference and go with a quicker hacky solution in the meantime in an attempt to avoid spending too much time on vulkano API holes. Some ideas for finishing the above implementation:

1. Expose the `Instance::pointers` method in vulkano and uncomment this.
2. Work out some other way to load the same function pointers that are owned by the instance.
3. Add the missing functionality for querying supported image formats to vulkano itself.
4. Wait until we switch away from vulkano in favour of gfx-hal and rendy one day.

In the meantime, I'm going to go ahead and finish implementing the solution discussed in #365.

**Comment by freesig** [comment]
Thanks for looking into this. I'll have a proper look into this soon.
