### ISSUE TITLE
[macOS] Background update issue

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#307]
I'm building a nannou application that has a gui window and a video output window.
I noticed that if the other window is in the background (ie not in focus) then the gui window slows to a crawl.
I think what is going on is that when the other window is in the background then it's waiting on the computers vsync callback. Which atleast on mac happens seems to happen really slowly.
This could be a consequence of waiting on the vulkano future.
Although I haven't noticed this in single window applications so it's a little weird. (I have another application that outputs midi and that seems to still work when in the background. If the update was blocking till vsync then this shouldn't work when in the background.

I'm not sure how to solve this.

It could also be that I have it set up incorrectly but I will keep digging.

**Comment by freesig** [comment]
Ok I can confirm this is happening with any nannou application that runs in the background on mac. I didn't notice it before because if an application is maximized then its never really in the background. 
I keep looking into it

**Comment by mitchmindtree** [comment]
Interesting! I wonder if this is related to josh's unstable frame rate issues on macos (I think #250 tracks that issue).

**Comment by freesig** [comment]
Yeh this could definitely be related. You can see it really clearly on instruments because it actually says `Foreground` / `Background` and you can see the vsync drop right off 
![image](https://user-images.githubusercontent.com/7286454/57521136-c7590500-7362-11e9-85e6-4244ac4ece90.png)
Here the pink lines are the mac calling for new frames. In the middle they are ages from each other and that is when I put the program in the background

**Comment by mitchmindtree** [comment]
Nice find!

Out of curiosity, are you seeing the same choppy behaviour when you change to the Rate the loop mode during setup? E.g. I think it's
```rust
app.set_loop_mode(LoopMode::rate_fps(60.0));
```
From memory the idea of the rate loop mode was to avoid blocking on the next frame and just submit at a certain rate. That said, this only makes a difference if MAILBOX present mode is supported which I don't think it is in MoltenVK in which case I think submitting the frame still might block on the previous one so not sure it will make a difference.

**Comment by freesig** [comment]
Yep this doesn't have any affect on MacOS but I think you're right, there isn't any MAILBOX on MoltenVK yet

**Comment by freesig** [comment]
I'm trying to think of something we could do to fix this.
Looks like MoltenVK [doesn't](https://github.com/KhronosGroup/MoltenVK/issues/581#issuecomment-488903202) support `MAILBOX`.
Perhaps we could make a mode that skips sending frames when your application is in the background on macos.
That way the update could still run and make progress. 
It's a pretty messy situation though
