### ISSUE TITLE
The Nannou Book - A place for guides, tutorials, examples and references.

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#309]
This is the main tracking issue for development of "The Nannou Book" - a central online book acting as a one-stop shop for all the information about Nannou someone could want.

Some contents that might be nice off the top of my head:

- **Why Nannou** - the motivations and goals behind the project, target audience, etc.
- **Getting Started** - a super friendly walk-through explaining how to get started with nannou assuming no prior knowledge about Rust or working with command lines. This might encompass both running the examples and how to setup custom nannou sketches/apps.
- **Guided Tutorials** - a suite of tutorials with specific goals like "Working with GUI", "Working with Audio", "Working with OSC", "Working with Lasers", "Integrating Gantz", etc where you walk through the creation of a simple demonstrative app with the reader, or perhaps multiple with increasing levels of advanced usage.
- **Developer Reference** - a guide to the architecture of Nannou's internals to help onboard new developers. Describes the layout of modules, how to navigate the reference, the scope of the main nannou crate i.e. the kinds of work that should go inside the main repo and the kinds that might be better off in separate repos, etc.
- **API Reference** - it would be nice if we could include the latest API reference in the book too for consistency, but it's probably easiest to leave this job to docs.rs as it already does such a good job. Either way, we should review the ease of navigation as some cases (like navigating the `Drawing` type docs) are currently quite tricky.
- **Showcases** - a collection of work made with nannou, perhaps ordered from most recent to the past. Users could do a PR to have their own nannou projects published.

@freesig @JoshuaBatty and I have been thinking that the easiest approach might be to use the [rust mdbook](https://github.com/rust-lang-nursery/mdBook) project to create something along the lines of "The Rust Programming Language" book, but much prettier with pictures, animations, and maybe interactivity if we can work it out one day. That said, if you have other ideas feel free to share them!

For some real-time discussion feel free to join the #book channel at the nannou slack.

Related issues:

#133 
#198

**Comment by tpltnt** [comment]
Should this be done here in the main framework repository or in a separate one (like openFrameworks does)?
(I personally think a separate repo is better)

**Comment by JoshuaBatty** [comment]
We will do it in a seperate repo, a new one under the nannou-org will be created for this asap.

**Comment by freesig** [comment]
Hey to get the ball rolling I have created https://github.com/nannou-org/guide
Just an empty repo but there is a [project](https://github.com/nannou-org/guide/projects/1) with a few issues to get started.

**Comment by tpltnt** [comment]
Now that the repo is created, can this issue be closed?

**Comment by mitchmindtree** [comment]
Good call @tpltnt, let's close it!
