### ISSUE TITLE
It seems it is required to import vulkano in order to declare shaders in v0.9

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#312]
cc @freesig 

Would be nice to confirm and if necessary fix this before v0.9.

**Comment by freesig** [comment]
Yeh this is essentially the problem:
```rust
mod vs {
    #[allow(unused_imports)]
    use std::sync::Arc;
    #[allow(unused_imports)]
    use std::vec::IntoIter as VecIntoIter;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor::DescriptorBufferDesc;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor::DescriptorDesc;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor::DescriptorDescTy;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor::DescriptorImageDesc;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor::DescriptorImageDescArray;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor::DescriptorImageDescDimensions;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor::ShaderStages;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor_set::DescriptorSet;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor_set::UnsafeDescriptorSet;
    #[allow(unused_imports)]
    use vulkano::descriptor::descriptor_set::UnsafeDescriptorSetLayout;
    #[allow(unused_imports)]
    use vulkano::descriptor::pipeline_layout::PipelineLayout;
    #[allow(unused_imports)]
    use vulkano::descriptor::pipeline_layout::PipelineLayoutDesc;
    #[allow(unused_imports)]
    use vulkano::descriptor::pipeline_layout::PipelineLayoutDescPcRange;
    #[allow(unused_imports)]
    use vulkano::device::Device;
    #[allow(unused_imports)]
    use vulkano::pipeline::shader::SpecializationConstants as SpecConstsTrait;
    #[allow(unused_imports)]
    use vulkano::pipeline::shader::SpecializationMapEntry;
    pub struct Shader {
        shader: ::std::sync::Arc<::vulkano::pipeline::shader::ShaderModule>,
    }
```
I think we might need to change this macro to `crate::vulkano` then do `use nannou::vulkano`.
I can't think of a way to do it without changing the macro because I think `use vulkano` only searches for external crates.

**Comment by freesig** [comment]
Yep I got this working by adding `crate` in front all `::vulkano` and `vulkano`.
However you need to add `pub use vulkano` to the nannou prelude so that this works for all current nannou code.
If you're happy with this solution I can chuck a PR onto vulkano.

**Comment by mitchmindtree** [comment]
Ahh, is that code above within the body of a `macro_rules!`? If so, we might be able to change it to use `$crate::` instead of `vulkano::`? I think [`$crate`](https://doc.rust-lang.org/1.7.0/book/macros.html#the-variable-crate) used to be a shorthand for "this crate, wherever it may be when this macros is invoked". I can't seem to find any reference to it in recent versions of the book though so maybe it was made reduntant with all the module changes in 2018? I'm pretty sure it should be possible to do this in a way that doesn't require any extra imports in nannou.

**Comment by freesig** [comment]
It's a proc_macro. It's actually hard coded into the codegen.rs file in vulkano-shadees.
I just put crate in front of all the `use vulkano` and it works fine. I think this was just missed by cargo fix because it's a macro

**Comment by freesig** [comment]
As in `use crate::vulkano`

**Comment by mitchmindtree** [comment]
Ahhhh of course, my bad, I forgot that it is a `proc_macro`. Yeah that sounds fine to me!

**Comment by freesig** [comment]
Ok the problem with this solution is that it's a breaking change. So every vulkano project will now need to add `use vulkano` to their `lib.rs` or `main.rs` if it's not already there.
I'm not sure they are going to go for this.
I really wish there was a way to say. use vulkano either from the crate or external.
Can you think of anyway to solve this without forcing everyone to add that line?

**Comment by freesig** [comment]
People are suggesting [this](https://github.com/rust-lang/rust/pull/55275) but I don't see how that helps. Struggling to find a good solution to this. Pretty much need $crate but for proc macro.
