### ISSUE TITLE
Copying the swapchain image

### ISSUE THREAD

**Issue by freesig** [nannou-org/nannou#313]
I'm having trouble copying the swapchain image to a buffer (or another image).
So when we create a framebuffer using the macro in vulkano and we set an image to `DontCare` or `Clear` then it sets the start_layout to `Undefined`
I thought this was ok because it would be transitioned in the renderpass before it's ever used but it's creating two seperate issues:
1. Vulkano is putting a memory barrier in to transition it to `Undefined` before every pass. Which is slow and pointless. Although won't crash anything unless you're in debug and try to use the image outside of a renderpass.
2. It's never actually set to `img.layout_initialized();` which causes a panic if you try to use it out side the pass.

I think we need to change the macro so that it doesn't actually set this to undefined and instead sets it to the first layout value that it's used for in the render pass. Which I think would be color`ColorAttachmentOptimal`

**Comment by freesig** [comment]
I have just removed this in a new push to the vulkan PR and it works now

**Comment by mitchmindtree** [comment]
Nice catch!
