### ISSUE TITLE
missing (real) MIDI support

### ISSUE THREAD

**Issue by tpltnt** [nannou-org/nannou#315]
Hi there,

the readme claims MIDI support. The only related code I could find is `OscMidiMessage` which handles MDI over OSC, but does not involve local MIDI devices. Either there should be support for MIDI devices which are attached locally or the claim should be removed (or at least made be less misleading.

Cheers,
tpltnt

**Comment by mitchmindtree** [comment]
Thanks for the issue!

I totally see where you are coming from - sorry for the confusion! The intention has been to add an example that demonstrates how easy it is to use MIDI via [`midir`](https://crates.io/crates/midir) in a nannou application (I've done so in the past and I believe @freesig has also, though neither projects are open source at the moment unfortunately). I think first writing some MIDI examples will also lead us toward any higher-level abstraction the nannou-org might be able to provide on top in a `nannou-midi` crate or something along those lines. It will also enable us to constantly test interop between the two crates via CI.

Perhaps it's worth separating out the features that nannou implements directly from those that a creative coder might be interested in that can be easily used via an external crate for clarity? Others that come to mind are DMX via sacn, serial via serial and TCP/UDP via std (each of these link to their respective crates in the README). This way we can still demonstrate to folks coming from environments like OF or Processing that MIDI is just as accessible in nannou as it is via an addon in one of those libraries, while still distinguishing between the support that we provide from within the organisation and those common creative coding protocol crates that work well alongside it.

We're currently working on [the guide](https://github.com/nannou-org/guide) with which we're planning on replacing the vast majority of the README contents soon, so this is a timely issue :+1:

**Comment by tpltnt** [comment]
I would like to see a working example since I am currently grinding my teeth on using `midir` and nannou to read MIDI messages. I can see some data, but failed to track/integrate it into the (global) model.

**Comment by lukors** [comment]
I would also like to have some example of using MIDI in Nannou.

You should absolutely clarify what is actually provided by Nannou and what is simply another crate that can be used with Nannou. I saw MIDI in the list and got quite confused when I found no mention of MIDI in the source code and no tutorials on using MIDI and no examples.

In [Why Nannou?](https://guide.nannou.cc/why_nannou.html) It says "Nannou aims to provide easy, cross-platform access to the things that artists need: [...] ☑ MIDI [...]". Considering the lack of examples, documentation etc., it would seem like Nannou does not provide any sort of easy access to MIDI other than "midir exists", which I don't think is thanks to the Nannou project. So I think that "☑" should be removed until the documentation/tutorials/examples have been added.

**Comment by mitchmindtree** [comment]
Thanks @lukors - perhaps this can be changed to something like this?

> - [ ] MIDI - *No friendly nannou API is provided yet, but cross-platform MIDI I/O is possible via [`midir`](https://crates.io/crates/midir).*

I'd be happy to land a PR that made this change.

**Comment by lukors** [comment]
Pull request up!

Sorry about my kind of harsh tone in the earlier message.

**Comment by mitchmindtree** [comment]
Closed via #668.
