### ISSUE TITLE
screenshot feature

### ISSUE THREAD

**Issue by tpltnt** [nannou-org/nannou#319]
Hi there,

as someone who tried nannou for some time now I would like to see a feature where I can render a frame into a file (on disk). This would enable further (offline) processing of the things created with nannou.

Cheers,
tpltnt

**Comment by mitchmindtree** [comment]
Totally agreed, this would be very nice feature!

This issue is closes related to #187 however this process would have changed since the switch to Vulkan. I think that @freesig and @MacTuitui have experimented with this, they might be able to provide more help?

**Comment by freesig** [comment]
Yeh I am working on this example. It's just been down the priority list with all the v0.9 going on. I have a really raw vulkano example that does this but it needs to be wrapped up nicely. I'll try and get a draft PR up this week

**Comment by tpltnt** [comment]
I would give v0.9 priority over this feature.

**Comment by tpltnt** [comment]
see also #187
