### ISSUE TITLE
Compile Error in conrod_vulkano on Mac OS Mojave

### ISSUE THREAD

**Issue by YmiYugy** [nannou-org/nannou#338]
```
    |
82  | /     vulkano_shaders::shader! {
83  | |     ty: "vertex",
84  | |         src: "
85  | | #version 450
...   |
102 | | "
103 | |     }
    | |_____^
    |
    = help: message: No Rust equivalent for a floating-point of width 32

error: aborting due to previous error

error: Could not compile `conrod_vulkano`.
```

This was with create a project code from the guide running nightly 1.37. It works on stable.
Should I rather open this question in the conrod project?

**Comment by mitchmindtree** [comment]
Thanks a lot for the report @YmiYugy!

Very curious that this is occurring only on the nightly 1.37 but not stable - I wonder if something has changed in the procedural macro API that might affect vulkano's `shader!` macro in the near future. I'll update to the latest nightly soon and do some investigating.

**Comment by rukai** [comment]
Hey guys, a quick look at the code shows that this is either some evil UB somewhere in vulkano or rustc is miscompiling things.

https://github.com/vulkano-rs/vulkano/blob/master/vulkano-shaders/src/structs.rs#L294 This branch can never be taken when width = 32, and yet it is taken...

**Comment by rukai** [comment]
Here is a fix, but its a breaking change :/ https://github.com/vulkano-rs/vulkano/pull/1209

I'd like to hear any other solutions.

**Comment by mitchmindtree** [comment]
Thanks for taking a look into this @rukai, really appreciate it! Requiring `Default` is implemented for vertex types seems easy enough to adapt to. I don't have the time to dig deeper just now but I'm happy with that solution if no one comes up with anything better in the meantime :+1:
