### ISSUE TITLE
Sense of dual licensing?

### ISSUE THREAD

**Issue by mkesper** [nannou-org/nannou#339]
Why did you choose to dual license using Apache and MIT?
As a user I always could choose to obey only the weaker license (MIT) so I don't see any gain here, just complications.

**Comment by mitchmindtree** [comment]
Thanks for the issue!

For the most part, we're trying to maintain as much flexibility and compatibility with the licensing of Rust itself, which is also [dual licensed](https://www.rust-lang.org/policies/licenses). Embarrassingly, I don't know enough about the difference between the two licenses to remember why the decision was made! You can read a little bit of discussion on the topic between some curious users and the founder of Rust [here](https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952).

If anyone else is reading this and has more knowledge on the topic, or if anyone else is confused by this please let us know! None of the founders of the project have much legal experience in this domain and would appreciate any advice.

**Comment by zelda-at-tempus** [comment]
When Rust was new, the team wanted Rust to be licensed under Apache 2.0 but needed to dual-license with MIT so the terms would be compatible with GPLv2. Most Rust projects have followed the Rust team's example, including Nannou.

More Reading:
* https://blog.gerv.net/2016/09/gplv2-combination-exception-for-the-apache-2-license/
* https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952
* https://opensource.stackexchange.com/questions/1881/against-what-does-the-apache-2-0-patent-clause-protect

**Comment by tpltnt** [comment]
I [added a section](https://github.com/nannou-org/guide/pull/30) in the guide based on your question and answers.

**Comment by mkesper** [comment]
Thanks for taking care!
