### ISSUE TITLE
Calling out to a compiled nannou binary from another process.

### ISSUE THREAD

**Issue by BorisKourt** [nannou-org/nannou#381]
Heya,

I am able to run a compiled Nannou binary from the terminal, including passing an image path as a parameter.

But when I try to automate this and shell out from another process the process returns:

```
thread 'main' panicked at 'failed to create vulkan instance:
LoadingError(LibraryLoadFailure("dlopen(libvulkan.1.dylib, 1): image not found"))',
src/libcore/result.rs:999:5
```
Is this an error specific to loading the VK library, or is this an error about loading an actual image? I am confused by the language here.

Thanks for any feedback!

**Comment by mitchmindtree** [comment]
Thanks for opening this!

I believe this error is related to finding the Vulkan loader which is necessary to create the Vulkan instance.

This is definitely non-intentional - I wonder if whatever code is in place to fetch the Vulkan loader is using a relative path somewhere or something.

I think @freesig might have a better idea of what could be causing this?

In the meantime, @BorisKourt could you possibly check to see if you run into this same behaviour with the vulkano examples [here](https://github.com/vulkano-rs/vulkano/tree/master/examples)? E.g. calling one of those compiled examples from your process rather than the nannou binary? This might help to work out whether the issue is in nannou or vulkano.

**Comment by BorisKourt** [comment]
Thanks for looking at this.
I made a release build of their triangle example and tried running it via my process, same error. It also runs fine via the command line.

**Comment by mitchmindtree** [comment]
Thanks for testing!

Just a heads up, we'll likely be the ones to have to write the fix either way as vulkano doesn't really have an active maintainer anymore. As a result of the lack of activity and some other issues, we're currently investigating switching to rendy #374, but we're continuing life support for vulkano in the meantime so hopefully this isn't too tricky to address :)

**Comment by BorisKourt** [comment]
I think I will refrain from cluttering that project with more issues then. Will take a look at the Rendy to-do.

**Comment by BorisKourt** [comment]
For fun I tried to move everything into one directory and run from source by shelling out to `cargo run --release <image/path>` assuming that this could maybe replicate the other conditions, but it still ended up with the same error.

Could this also be platform specific? I am on a Mac.

**Comment by freesig** [comment]
I believe this is an issue with the sdk needing to be in `DYLD_LIBRARY_PATH`. MacOS has made this pretty hard lately.
If you call `echo $DYLD_LIBRARY_PATH` from the shell that you are trying to make this work in you should see `/Users/username/.vulkan_sdk/macOS/lib:`.
If that's not the case make sure that shell is running your `.bash_profile` or wherever the vulkan env vars are.
If that is the case I think this is MacOS preventing DYLD_LIBRARY_PATH from being passed to a child process.
You have two options at this point disable MacOS SIP or get the child process to set this env var before running the binary everytime like:
shell script
1. set `DYLD_LIBRARY_PATH` to `/Users/username/.vulkan_sdk/macOS/lib:`
2. run binary

This is how I solved a similar problem using the fish shell
https://github.com/nannou-org/nannou/issues/261#issuecomment-514846097

**Comment by BorisKourt** [comment]
Ah thanks for that, I was able to set the env var in the child process and everything ran perfectly. I am closing this as I think it solves the problem for MacOS users at this time.
