### ISSUE TITLE
Invalid mouse position when switching window

### ISSUE THREAD

**Issue by mft-ableton** [nannou-org/nannou#392]
When at least two windows are being used, when you click inside another window (without moving the mouse after clicking), `app.mouse.window` and `app.mouse.buttons` (pressed state)  are updated, but not `app.mouse.x` nor `app.mouse.y`. 
So these two values are invalid, as well as the position in the pressed state of the mouse (which uses the position of `app.mouse`).
This behaviour can be observed looking at the output of the multi window example `multi_window.rs`.

**Comment by mitchmindtree** [comment]
Would you mind also sharing which platform you're on? This might help to work out the source of the issue in the necessary platform on winit, and will allow us to check if this is the case on other platforms as well.

**Comment by mft-ableton** [comment]
Sure: macOS Mojave, Version 10.14.6

**Comment by JoshuaBatty** [comment]
This seems to be addressed now with the PR #452 to wgpu. Now experiencing some slow frame issues but i'll open another issue for that.
