### ISSUE TITLE
Text drawn with draw.text() is always displayed in the middle regardless of positioning added

### ISSUE THREAD

**Issue by ErikNatanael** [nannou-org/nannou#401]
This code
`draw.text("hello you sloppy jalopy").x(100.0).y(-1000000.0);`
or this:
```
draw.rect()
.xy(rect.pos)
.w(rect.width)
.h(rect.height)
.rgb(rect.color.0, rect.color.1, rect.color.2 );

draw.text(rect.text.as_str())
.xy(rect.pos)
.rgb(0., 1., 0.);
```
always draws the text at the center of the window (while the rectangle is drawn at the right position).

Pastebin of the full code used (bits of example code mashed together mostly): https://paste.rs/yjW

Using nannou 0.11 on Ubuntu 19.04.

**Comment by mitchmindtree** [comment]
Thanks for the report! You are absolutely right, this was a sloppy jalopy on my behalf. I have a PR ready to go, I shall push it now!
