### ISSUE TITLE
Should the Vector* types have utility functions like from_angle, magnitude, and magnitude_squared?

### ISSUE THREAD

**Issue by benweedon** [nannou-org/nannou#420]
Hey! I've been familiarizing myself with nannou, and I was thinking it might be nice to add some utility functions to the Vector* types. The ones that I came across needing were:

- `from_angle`, to create a unit vector from a given angle in radians
- `magnitude` to return the magnitude of the vector
- `magnitude_squared` to return the magnitude squared of the vector, i.e. `a^2 + b^2`. This is good when all you care about is the magnitude of this vector relative to other vectors, since you don't have to perform the expensive square root operation.

I'd be happy to tackle these myself if people would like these (or other) utility functions added!

**Comment by mitchmindtree** [comment]
Thanks for the issue @benweedon!

There are [`magnitude`](https://docs.rs/nannou/0.11.1/nannou/prelude/trait.InnerSpace.html#method.magnitude) and [`magnitude2`](https://docs.rs/nannou/0.11.1/nannou/prelude/trait.InnerSpace.html#method.magnitude2) methods provided via the `InnerSpace`  trait which is included within nannou's prelude - does this work for you? Perhaps the methods weren't showing up in your auto-completion? Please let us know if that's the case, I think sometimes the currently available Rust IDE tooling fails to resolve traits properly. In that case, perhaps we can add these as inherent methods on the `Vector` types to improve discoverability.

As for `from_angle`, that sounds really useful! I believe you can do this in some convoluted way using that the `cgmath` library that nannou currently uses under the hood, but it would be nice to provide a simplified constructor like you describe directly on the `Vector` types.

**Comment by benweedon** [comment]
Oh, cool, thanks for pointing those two out! Yeah, my autocomplete didn't show them, and I missed that they were part of a trait implementation! Adding them as methods directly would definitely improve discoverability, but if there's a trait that covers those methods it's also nice to have them as part of the trait. I'm not super familiar with rust docs and if trait implementations can be listed more prominently on the type's page. I feel like this is an issue for a lot of nannou types, since they provide a lot of functionality through traits that are specific to nannou's dependencies. I guess I could have discovered the methods better if I had just searched the entire docs site for "magnitude" though :)

I'm currently creating a unit vector from an angle with `vec2(angle.cos(), angle.sin())`, which seems to work well. I think that should work for Vector2. Vector3 requires two angles `a` and `b`, and I think `vec3(a.cos()*b.cos(), b.sin(), a.sin()*b.cos())` would work for that, although I haven't verified it. There should be a similar formula for Vector4. I can look into it.
