### ISSUE TITLE
Additional dependencies required on Ubuntu

### ISSUE THREAD

**Issue by timClicks** [nannou-org/nannou#442]
Hi there, I needed to add a few header dependencies before I could get started:

```
sudo apt install libxcb-shape0-dev
sudo apt install libxcb-xfixes0-dev
```

**Comment by ignlg** [comment]
Would you mind opening a PR to add it to the `Platform-specific Setup` html? Thanks :)

**Comment by timClicks** [comment]
Done, thanks for the tip :)
