### ISSUE TITLE
Re-structure nannou repo to be a cargo workspace

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#449]
Currently this repo contains three crates:

1. `nannou`
2. `nannou-new` - a super basic project generator
3. `nannou-package` - a super basic build packager

`nannou` occupies the top-level and currently contains the other two as sub-directories. It might be more practical to make a `nannou` sub-directory so that all three are at the top-level and include a `Cargo.toml` with a workspace containing all three. This should potentially ease compile times a bit.

If we go down this route, it might also be worth moving the `nannou_audio`, `nannou_laser`, `nannou_osc` and `nannou_timeline` crates into this repo too. This may make development on each a lot easier by sharing the build artifacts between all crates and make it easier to test all crates and ensure each remain compatible and up-to-date. It might possibly also improve visibility of the `nannou_*` crates.

Finally, we could potentially move the `examples` directory to the top-level as well so that they remain easily visible. It might be nice to merge all examples for audio, laser, osc, etc into one place like this.

cc @freesig @JoshuaBatty thoughts?

**Comment by JoshuaBatty** [comment]
Nice, i'm a fan of this idea. I think the nannou_* crates would get more attention than they currently get residing in their own repos. Agree it would also make development a lot easier if we can share build artifacts.

**Comment by mitchmindtree** [comment]
As a part of this restructure, it might be a good idea to publish updates to all crates so that the versions match against all nannou crates? This might make it easier for users to know right away which versions are compatible, rather than having to check what the latest version of each nannou crate is and hoping they still work together. This might mean we end up doing more version updates in general across all the crates, but I don't think there's any harm in this.

**Comment by mitchmindtree** [comment]
Closed via #497.
