### ISSUE TITLE
Rename window builder methods from `with_*` to `*`

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#451]
It seems a little needlessly verbose for each of the builder methods to begin with `with_`. It is clear that each of these methods are specifying some properties of the window being built either way. It would be nice to rename the builder methods to remove `with_`.

E.g.:

- `with_title` -> `title`
- `with_fullscreen` -> `fullscreen`
- `with_dimensions` -> `dimensions`

etc.

**Comment by anchnk** [comment]
I am willing to give it a try if that's ok. Let me know if you are interested in offloading it

**Comment by mitchmindtree** [comment]
That would be great!

**Comment by anchnk** [comment]
PR is pushed and ready for review. On a side note there are no tests available for those methods:

- with_min_dimensions
- with_max_dimensions
- with_fullscreen
- with_maximized
- with_visibility
- with_transparency
- with_decorations
- with_multitouch

I don't know what could be done but that would be nice to implement some testing strategy for these as well.
