### ISSUE TITLE
[wgpu] Synchronising `Buffer::map_read_async` calls and encoded commands

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#459]
*This issue is related to the wgpu branch at #452.*

I'm currently working on a `read_texture_to_bytes` function that looks something like this:
```rust
        fn read_texture_to_bytes<F>(
            texture: &wgpu::Texture,
            device: &wgpu::Device,
            encoder: &mut wgpu::CommandEncoder,
            callback: F,
        )
        where
            F: 'static + FnOnce(wgpu::BufferMapAsyncResult<&[u8]>),
        {
            // 1. device.create_buffer
            // 2. encoder.copy_texture_to_buffer
            // 3. buffer.map_read_async(0, n, callback)
        }
```
The intention is to provide a simple function for a potentially common operation (e.g. mapping and reading a texture from the CPU). Use cases might include: recording an animated sketch to a sequence of image files, sending frames of graphics over the network, routing frames of graphics to VJ software.

However, I'm running into issues w.r.t achieving my desired synchronisation of the `buffer.map_read_async` call. I'd like to be able to say something like:

"do `buffer.map_read_async` *after* the encoded `copy_texture_to_buffer` completes"

however it seems the only way to ensure this is to `submit` the encoded command buffer before calling `buffer.map_read_async`. This is a bit troublesome as I'd like for the user to be able to go on encoding more commands with the provided `encoder`. The desire for this is due to the API I'm attempting to expose for nannou's "redraw requested" stage. To give a little more context, the API we're currently exposing from nannou's `view` function looks like this:

```rust
fn view(app: &App, model: &Model, frame: &Frame) {
}
```

where
- `app` is state managed by nannou (windowing, devices, I/O stuff)
- `model` is user state and
- `frame` represents the texture that we are writing to.

The `frame` has a single `wgpu::CommandEncoder`, and the idea is that during the call to `view`, the user encodes their commands (copies, render passes, etc) which are finally submitted to the queue after `view` completes in one big command buffer. Seeing as this API hides the submission of the command buffer from the user until after `view` returns, this makes it difficult to provide an API that allows the user to read the textures.

The original motivation for encouraging the use of a single command buffer like this was to minimize the number of command buffer "submissions" to improve performance. However, it seems it may be necessary to allow for multiple submissions in order to support cases where we want to map a buffer between commands.

One smaller change that could allow us to get quite far might be to keep the restriction within the `view` call that requires building a single command buffer, but to allow for it to be submitted *before* the `view` function returns. This would allow users to submit their command buffer and then make their `map_read_async` calls before the end of the `view` function. That said, we would need to be careful in documenting the requirement that the command buffer is submitted before map calls are made.

Does this sound like a reasonable solution? Or is there perhaps a better way to go about this synchronisation between commands and calls to `map_read/write_async`?

cc @kvark any advice or thoughts you might have would be appreciated!

**Comment by kvark** [comment]
(Talked this over on Matrix. All that's required from our side is that `map_read_async` is only called after `submit()`.)

**Comment by mitchmindtree** [comment]
Closed via [this commit](https://github.com/nannou-org/nannou/pull/452/commits/2167d3f82f3f89a35fb09b8b1061e17f2b75f33a).
