### ISSUE TITLE
Broken WebGPU links on examples README.md

### ISSUE THREAD

**Issue by manugildev** [nannou-org/nannou#473]
In https://github.com/manugildev/nannou/tree/master/examples, the links related to webgpu are all broken and pointing to an outdated resource inside a non-existent "vulkan" folder.

**Comment by manugildev** [comment]
PR waiting to be merged: https://github.com/nannou-org/nannou/pull/474

**Comment by mitchmindtree** [comment]
Closed via #474 - thanks again!
