### ISSUE TITLE
rgb_to_hsl can return NaN's 

### ISSUE THREAD

**Issue by JoshuaBatty** [nannou-org/nannou#494]
Can replicate this behaviour by running the p_1_2_2_01 example and using SortMode::Saturation

**Comment by mitchmindtree** [comment]
Just to clarify for future readers, I think this function is actually in the `conrod_core` crate. Normally in nannou, it can be accessed via `nannou::ui::color::rgb_to_hsl` or something like this, but in general it is preferable to use the `rgb.into()` and `Hsl::from(rgb)` functions instead.

**Comment by mitchmindtree** [comment]
Going to close this as its bessed addressed in `conrod_core`.
