### ISSUE TITLE
compile fail on os x high sierra

### ISSUE THREAD

**Issue by jtnimoy** [nannou-org/nannou#523]
rust is installed with MacPorts
rustc 1.25.0 (84203cac6 2018-03-25)
I'm on a 2016 Macbook
---
My goal was to clone and build nannou per instructions at https://guide.nannou.cc/getting_started/running_examples.html

i followed the commands:

```
git clone https://github.com/nannou-org/nannou
cd nannou
cargo run --release --example draw
```

the terminal returned the following:

```
error: manifest path `/Users/jtnimoy/Desktop/nannou/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

and so I guessed I should cd into examples, then try the cargo run command again.

```
~/Desktop/nannou/examples $ cargo run --release --example draw
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/nannou-org/hotglsl`
    Updating git repository `https://github.com/nannou-org/isf`
error: no matching package named `wgn` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `wgpu v0.4.0`
    ... which is depended on by `conrod_wgpu v0.69.0`
    ... which is depended on by `nannou v0.13.1 (file:///Users/jtnimoy/Desktop/nannou/nannou)`
    ... which is depended on by `nature_of_code v0.1.0 (file:///Users/jtnimoy/Desktop/nannou/nature_of_code)`
```

I was not able to find the wgn crate anywhere.

**Comment by jtnimoy** [comment]
rustup 1.11.0 (e751ff9f8 2018-02-13)

**Comment by JoshuaBatty** [comment]
Hi @jtnimoy ! great to hear you're bringing out nannou again :) 

That version of Rust is rather old now. Can I suggest running `rustup update` to update rust to the lastest version first?

Then in your nannou directly, run `cargo clean` then `cargo update`. The next time you build a nannou project everything should work nicely with each other again. Please let me know you have any troubles!

**Comment by jtnimoy** [comment]
Yes that worked 100%. I did a `rustup install nightly;rustup default nightly`

also, yes -- very pleased to be back around here again!
