### ISSUE TITLE
Maybe mistakes in guide > "create a project"

### ISSUE THREAD

**Issue by jtnimoy** [nannou-org/nannou#524]
I followed the directions on this page:

https://guide.nannou.cc/getting_started/create_a_project.html

and I noticed in the source of that HTML, that the first line of code is being hidden because it's in a span with class "boring".

```
extern crate nannou;
use nannou::prelude::*;
```

Also, I found that this line:

```
fn view(_app: &App, _model: &Model, frame: Frame){
```
prefers to have Frame passed as a pointer.
```
fn view(_app: &App, _model: &Model, frame: &Frame){
```

My versions of things:
nightly-x86_64-apple-darwin (default)
rustup 1.11.0 (e751ff9f8 2018-02-13)
rustc 1.44.0-nightly (42abbd887 2020-04-07)

**Comment by mitchmindtree** [comment]
Thanks for the issue @jtnimoy !

Interesting! That `extern crate nannou;` line should no longer be necessary as of the 2018 edition of rust - the version you have is much newer so I don't think your Rust version is the problem. Was the lack of this line causing you a compile error somewhere?

Similarly, in the latest version of `nannou` we no longer require that the frame is passed by reference, so the former where `Frame` is passed by value should be correct.

I wonder if perhaps you are attempting to run an old project and running into errors? If that's the case, you might need a `cargo update` while `cd`'d into the project. The `cargo update` command is local to each project, and tells cargo to check for the latest version of each of the dependencies as per the semver version specified for each in the `Cargo.toml`. If this doesn't help, it might be the case that the old project needs to have a `edition = "2018"` entry under the `[package]` table in the `Cargo.toml`. This tells Rust that the project is built to handle new 2018 Rust features - one of which is that `extern crate` is no longer required for dependencies. Finally if this doesn't do the trick, is there a chance that your `nannou` dependency is pointing to an older version? To point to the latest published version, you can use
```toml
nannou = "0.13"
```
Under the `[dependencies]` section of your project. It's also good to be aware that some changes on the git master have not yet been published! If you'd like to use the git master, you can use this as an alternative:
```toml
nannou = { git = "https://github.com/nannou-org/nannou", branch = "master" }
```

Also in case you're curious, we generate the HTML for the guide from a markdown book which can be found [here](https://github.com/nannou-org/nannou/tree/master/guide). It might be handy if you come across the need to check for hidden lines or something like this again. 

I hope this helps a little! If not, please let me know and I'll keep thinking! Excited to have you around again JT :) feel free to keep opening issues as you come across things that seem odd, etc - they're very welcome!

**Comment by jtnimoy** [comment]
Thank you for the response, and doing a `cargo update` made the difference with passing Frame by reference. Here is the error I get when I omit extern crate nannou . . .

```
JTs-MacBook:my-project jtnimoy$ cargo run
   Compiling my-project v0.1.0 (/Users/jtnimoy/Desktop/rust-learning/my-project)
error[E0433]: failed to resolve: maybe a missing crate `nannou`?
 --> src/main.rs:1:5
  |
1 | use nannou::prelude::*;
  |     ^^^^^^ maybe a missing crate `nannou`?
```

**Comment by mitchmindtree** [comment]
Alright great to hear we fixed the first one!

As for the extern crate issue: In the `Cargo.toml` of `my-project`, could you try adding the following line under the `[package]` table?

```toml
edition = "2018"
```
After adding the line, the top of your `Cargo.toml` should look something like this:
```toml
[package]
name = "my-project"
version = "0.1.0"
authors = ["JT <jt-email.com>"]
edition = "2018"
```

This should indicate to cargo that you are using the 2018 (aka most recent) edition of rust.

Let me know how this goes! If you have no luck with this, my next thought would be to check whether or not you have a conflicting version of `rustc` or `cargo` in your PATH. I noticed in #523 you mentioned you originally installed rust via macports, but also that you were using rustup. Normally, `rustup` is the recommended way of installing your Rust toolchain which includes both `rustc` and `cargo`. It's particularly handy as it lets you have multiple rust "toolchains" installed and to switch between them with ease. This can be handy for e.g. if you require adding a cross-compiling targets, or if you require testing on both nightly and stable for a library that you're writing, etc. Anyways, let me know how you go :)

**Comment by jtnimoy** [comment]
Yes, that was it! Adding `edition = "2018"` to the package section of Cargo.toml allowed me to remove the extern line!
