### ISSUE TITLE
Window::capture_frame sometimes does not complete if LoopMode is NTimes

### ISSUE THREAD

**Issue by ericyd** [nannou-org/nannou#525]
Use-case: I want to draw some simple 2D images with nannou and save the drawing to an image file.

Steps to reproduce
1. Clone this repo
2. Edit [draw_capture](https://github.com/nannou-org/nannou/blob/d6d5d38a6b617cf976f857b79c3c8bb233a22aad/examples/draw/draw_capture.rs) example to have the following modification
```
fn view(app: &App, frame: Frame) {
  app.set_loop_mode(LoopMode::loop_ntimes(2)); // <--- added
  let draw = app.draw();
```
3. Run example

The directory for `draw_capture` will be created but an image will never be saved to that directory (at least within a reasonable time, ~1 minute)

OS: Mac, 10.15.2
Nannou version: 0.13.0

Note: I wrote "sometimes" in the issue title because some sketches seem to work fine with 2 loops, some require 3, and some seem to never successfully write the image. I haven't been able to discern a strong pattern.

**Comment by mitchmindtree** [comment]
Thanks for the issue @ericyd !

I believe the issue you are running into here is that nannou does not block on `exit` and wait until all frames have been captured. This is certainly something nannou should do, and by digging deeper I'm noticing we have two main issues:

1. The `capture_frame` method submits a function to the wgpu API that only gets called when the device is polled and the GPU has finished processing the GPU command queue with which the captured frame is drawn. By default, the GPU device is only polled upon queue submission, and queue submission only occurs when the commands for drawing to the frame are submitted. This means that writing the frame to disk does not occur until *at least* the following `view` call. Something I think we can do to remedy this is to keep track of the number of frames currently being captured and ensure that, when a nannou app exits, we repeatedly poll the GPU device until all frames have been written to disk.
2. In the case that the user is using a `capture_frame_threaded`, we must ensure that we properly join with the thread used to write frames to disk. This is much easier to address as the `TextureCapturer` we use internally already provides an API for achieving this.

Thanks again for the report! I doubt you are the only person to have run into this :)

**Comment by ericyd** [comment]
I really wish I knew rust well enough to attempt a PR for this - I would love to contribute but no idea how to achieve either of these solutions.

Have been using nannou for a few weeks now and really enjoying it, thanks for all your work on this project. The examples have been priceless since its a newer project 👍

**Comment by mitchmindtree** [comment]
> I really wish I knew rust well enough to attempt a PR for this - I would love to contribute but no idea how to achieve either of these solutions.

No worries at all! Even opening an issue is a big help. I will make a note to look into this before we release 0.14.

Really glad you've been enjoying nannou otherwise! That means a lot :)
