### ISSUE TITLE
Should capture_frame_threaded use threaded: true?

### ISSUE THREAD

**Issue by ericyd** [nannou-org/nannou#526]
I would normally just create a PR for this but I'm really unfamiliar with threading and pretty new to Rust in general. 

I was looking through the source and it felt weird to me that the methods for `Window::capture_frame` and `Window::capture_frame_threaded` were essentially identical.

https://github.com/nannou-org/nannou/blob/master/nannou/src/window.rs#L1350
https://github.com/nannou-org/nannou/blob/master/nannou/src/window.rs#L1365

I wondered, perhaps capture_frame_threaded should call
```
self.capture_frame_with_threaded(path.as_ref(), true); // change false to true
```
?

**Comment by mitchmindtree** [comment]
Thanks for opening this @ericyd and sorry you had to run into this! Yes you are absolutely right, this is an embarrassing one :worried: The method is quite a recent addition and looks like it has slipped through the cracks! I'll reply to your other issue momentarily :+1:
