### ISSUE TITLE
Allow for specifying default initial `LoopMode` in app and sketch builder

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#528]
This would allow for specifying alternative loop modes in sketches without the need to do so in the `view` function, the behaviour of which can be a bit ambiguous.

**Comment by gmunk** [comment]
I'm interested in doing this, in fact I've made some progress, if you guys want you can assign it to me and I'll try and open a PR soon.

**Comment by mitchmindtree** [comment]
That would be great!
