### ISSUE TITLE
examples lead to wgpu-native panick

### ISSUE THREAD

**Issue by sprajagopal** [nannou-org/nannou#538]
Hello,

`cargo 1.44.0-nightly (390e8f245 2020-04-07)`

I cloned the repo and

`cargo run --release --example draw_mesh`

which leads to:

```
    Finished release [optimized] target(s) in 0.26s
     Running target/release/examples/draw_mesh
thread 'main' panicked at 'called Option::unwrap() on a None value', /home/prasanna/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: wgpu_request_adapter
  15: wgpu::Adapter::request
  16: nannou::wgpu::device_map::AdapterMap::get_or_request
  17: nannou::window::Builder::build
  18: nannou::app::SketchBuilder<E>::run
  19: draw_mesh::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  23: std::panicking::try
             at src/libstd/panicking.rs:274
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.


```

Things I have checked:
1. yes, I have `vulkan-sdk` installed
2. yes, I tried with a few other examples also, particularly `all_functions`

**Comment by mitchmindtree** [comment]
Thanks for the issue @sprajagopal !

Just to clarify, this is occurring on Linux yes? Do you happen to have `vulkaninfo` installed? If so, could you run it and share its output?

It looks like there is no available device on the system that satisfies the default `wgpu::Adapter` parameters requested by nannou. Unfortunately `wgpu` does not yet expose an API for retrieving device capabilities, so nannou must do its best to use some reasonable defaults.

One of these defaults is to enable 4x multi-sampling. Could you try running the `wgpu_triangle_raw.rs` example and let me know if this succeeds on your system? If so, you might be able to get other examples working by disabling multisampling.

For example, in the `nannou_basics/simple_sindow.rs` example the window is built like this:
```rust
    let _window = app
        .new_window()
        .size(512, 512)
        .title("nannou")
        .view(view)
        .event(event)
        .build()
        .unwrap();
```
You can disable multisampling by adding the following builder method:
```rust
    let _window = app
        .new_window()
        .size(512, 512)
        .title("nannou")
        .msaa_samples(1)
        .view(view)
        .event(event)
        .build()
        .unwrap();
```

Let me know how you go!

**Comment by sprajagopal** [comment]
Hello,
Sorry about the delay.
This is my `vulkaninfo`
`
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /build/vulkan-tools-1.2.135.0~rc2/vulkaninfo/vulkaninfo.h:624:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
`
I also tried disabling multi-sampling but that gave out this:
`
   Compiling examples v0.1.0 (/home/prasanna/Dropbox/nannou/nannou/examples)
    Finished release [optimized] target(s) in 10.53s
     Running `target/release/examples/simple_window`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/prasanna/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

So I think my `vulkan` drivers are not installed properly. I'll try and figure out what's the issue. Thanks~

**Comment by mitchmindtree** [comment]
Going to close for now, but feel free to re-open if you are still running into this bug after updating your drivers :+1:
