### ISSUE TITLE
Boid in NOC examples have wrong rotation

### ISSUE THREAD

**Issue by MarkuBu** [nannou-org/nannou#551]
Hi,
I tried some Nature of Code examples and I noticed, that the boids (vehicle) in the examples of chapter 6 are rotated in the wrong way

I had to change `rotate(theta)` to `rotate(-theta)` for correct orientation.

Maybe it is an issue with the operation system. I'm running Linux and I heard in the Amethyst Discord Channel that there might be an issue between different implementations of the graphic driver or something like this

**Comment by mitchmindtree** [comment]
Thanks for the report @MarkuBu !

I just tested locally and can confirm it's not just you - definitely a bug!

cc @JoshuaBatty

**Comment by JoshuaBatty** [comment]
Thanks for reporting this bug @MarkuBu . This should be fixed now.
