### ISSUE TITLE
Move "Sketch vs. App" section from "Draw a Nannou Sketch" into its own mini tutorial

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#557]
I think this is one of those FAQs that would be great to have its own little dedicated page. We could point to "Draw a Nannou Sketch" and "Anatomy of a Nannou App" respectively for more info.

**Comment by madskjeldgaard** [comment]
Yes ! And perhaps with a few extra details about what that distinction means 




On Tue, Apr 21, 2020 at 3:56 PM +0200, "mitchmindtree" <notifications@github.com> wrote:















I think this is one of those FAQs that would be great to have its own little dedicated page. We could point to "Draw a Nannou Sketch" and "Anatomy of a Nannou App" respectively for more info.
