### ISSUE TITLE
Typo in resizable method

### ISSUE THREAD

**Issue by jembishop** [nannou-org/nannou#573]
https://github.com/nannou-org/nannou/blob/e55ce80dc1504fb95a2ac9ae33e5a1aca3bdefa9/nannou/src/window.rs#L869

This looks like a typo for resizable?

**Comment by mitchmindtree** [comment]
Thanks for the issue!

Sure is, good spot! Would you be up for opening a PR to fix this?

**Comment by jembishop** [comment]
Thanks, Yes I will raise a PR

**Comment by jembishop** [comment]
https://github.com/nannou-org/nannou/pull/574 raised
