### ISSUE TITLE
Can I specify the size of drawing area, not the window size?

### ISSUE THREAD

**Issue by yutannihilation** [nannou-org/nannou#575]
I wanted a square window to fill with squares, but setting `size(500, 500)` doesn't give me the exact one; the outer size of the window is 500 x 500, but the drawing area is a bit shorter because there's a space for top bar.

For example, this code

``` rust
use nannou::prelude::*;

fn main() {
    nannou::sketch(view).size(500, 500).run();
}

fn view(app: &App, frame: Frame) {
    app.set_loop_mode(LoopMode::loop_once());
    let draw = app.draw();
    let win = app.window_rect();
    println!("The window is {} x {}", win.w(), win.h());
    draw.to_frame(app, &frame).unwrap();
}
```

prints these two lines on console:

```
The window is 500 x 500
The window is 500 x 470
```

It seems the window is actually created as 500 x 500, but then it somehow shrinks probably for the top bar. Is it possible to specify the size of the drawing area from nannou? I guess this might be a complicated issue depending on the desktop environment (I'm using GNOME3 (Wayland) on Manjaro Linux), but it's great if I can.

**Comment by mitchmindtree** [comment]
Thanks for the issue @yutannihilation!

Hmm this is a really strange one! Looking through nannou's code we can see that `size` *does* indeed [specify the inner size](https://github.com/nannou-org/nannou/blob/master/nannou/src/window.rs#L847) of the winit window.

I'm also using GNOME3 Wayland (though on NixOS), however if I remove the `set_loop_mode` from your code and allow nannou to continue to loop, the window stays at 500x500 consistently. Is there any chance you have a window manager of some sort that might be automatically adjusting the window size? If not, it might be worth browsing through the [winit issue](https://github.com/rust-windowing/winit) to see if you can find anything on this. Certainly a strange one!

**Comment by yutannihilation** [comment]
Oh, thanks, then it sounds something is wrong with my setup... 

> Is there any chance you have a window manager of some sort that might be automatically adjusting the window size?

I'm just using the default Mutter and I think it doesn't behave so. But I found the window size changes if I move the window to the second display, so the window manger might be the cause... Anyway, thanks for the hints! I'll check my settings and look into winit issue.

In case a visual example is useful, here's what I get when I try to draw 50 x 50 window:

![Screenshot from 2020-04-27 22-05-24](https://user-images.githubusercontent.com/1978793/80375456-5001e580-88d3-11ea-8293-26fa17fb76fa.png)

**Comment by yutannihilation** [comment]
> I'm just using the default Mutter and I think it doesn't behave so

Sorry, it seems I was wrong here. It's Mutter that behaves unexpectedly.

I tried this code

``` rust
use nannou::prelude::*;

fn main() {
    nannou::app(model).event(event).view(view).run();
}

struct Model {}

fn model(app: &App) -> Model {
    app.new_window().size(500, 500).build().unwrap();
    // app.main_window().set_resizable(false);
    Model {}
}

fn event(_app: &App, _model: &mut Model, event: Event) {
    println!("{:?}", event);
}

fn view(app: &App, _model: &Model, frame: Frame) {
    app.set_loop_mode(LoopMode::loop_once());
    let draw = app.draw();
    let win = app.window_rect();
    println!("The window is {} x {}", win.w(), win.h());
    draw.to_frame(app, &frame).unwrap();
}
```

and got this:

``` rust
Update(Update { since_last: 98.396µs, since_start: 98.396µs })
The window is 500 x 500
WindowEvent { id: WindowId(Wayland(WindowId(94718048388896))), simple: Some(Resized(Vector2 { x: 500.0, y: 470.0 })) }
WindowEvent { id: WindowId(Wayland(WindowId(94718048388896))), simple: Some(Focused) }
The window is 500 x 470
```

and, if I uncommented `app.main_window().set_resizable(false);`, I can got this:

``` rust
Update(Update { since_last: 106.53µs, since_start: 106.53µs })
The window is 500 x 500
WindowEvent { id: WindowId(Wayland(WindowId(94376606340896))), simple: Some(Focused) }
The window is 500 x 500
WindowEvent { id: WindowId(Wayland(WindowId(94376606340896))), simple: Some(Resized(Vector2 { x: 500.0, y: 530.0 })) }
The window is 500 x 530
```

The latter means the window manager (Mutter?) resizes the window even when the resize is not allowed. I feel this indicates the window manager have different semantics about such concepts as "resize" and "inner size."

I have very little knowledge about how these things work, so I might be wrong... Probably I should file an issue on winit's side (as there seems no such ones yet), but it might take some time to write a winit version of the example. May I keep this issue open for a while?

**Comment by yutannihilation** [comment]
After two weeks, I still have no idea how to report this to winit... So, let me just close this for now as this is not a big issue to me at the moment and there seems no one faces the same problem. Anyway, thanks for your help!
