### ISSUE TITLE
Alpha index seems off.

### ISSUE THREAD

**Issue by MacTuitui** [nannou-org/nannou#578]
Hello again, 
I have this tiny bug that is creeping on me recently, so I made the simplest example I could:

```rust
use nannou::prelude::*;

fn main() {
    nannou::sketch(view).run()
}

fn view(app: &App, frame: Frame) {
    let draw = app.draw();
    draw.background().color(CORNFLOWERBLUE);

    let mut points = Vec::new();
    points.push((vec2(-100.0,-100.0), srgba(1.0,1.0,1.0,0.0)));
    points.push((vec2( 100.0,-100.0), srgba(1.0,1.0,1.0,0.0)));
    points.push((vec2( 100.0, 100.0), srgba(1.0,1.0,1.0,0.0)));
    points.push((vec2(-100.0, 100.0), srgba(1.0,1.0,1.0,1.0)));
    draw.polyline().points_colored(points);

    draw.to_frame(app, &frame).unwrap();
}
```

Just a line with four points laid out in a square, the first three should be completely transparent, so I expect this to draw only a line between the last two points, with a smooth alpha transition.

However I get this:
![Screen Shot 2020-04-28 at 15 14 37](https://user-images.githubusercontent.com/1924395/80453340-019c2780-8963-11ea-8105-cee90a5de61f.png)

Where it looks like the alpha for the first point is not set correctly. 

Moreover, if I change the alpha values to:
```rust
    points.push((vec2(-100.0,-100.0), srgba(1.0,1.0,1.0,1.0)));
    points.push((vec2( 100.0,-100.0), srgba(1.0,1.0,1.0,0.0)));
    points.push((vec2( 100.0, 100.0), srgba(1.0,1.0,1.0,0.0)));
    points.push((vec2(-100.0, 100.0), srgba(1.0,1.0,1.0,0.0)));
```
This time, I get nothing. So somehow the first point ends up with the alpha of the last point?

You can play around with which points get which alpha, with three points and every other combination possible, but it looks like there is a shift in the alpha index somehow...

**Comment by mitchmindtree** [comment]
Ahhh interesting thanks for opening this!

I think this is possibly something to do with lyon's attribute interpolation or the way that we are using it. Out of curiosity, is there any difference if you use `.join_round()` or `.caps_round()` on the polyline?

Thanks heaps for providing a test case!

**Comment by MacTuitui** [comment]
No luck, `join_round` and `caps_round` have no influence here.

**Comment by MacTuitui** [comment]
Nical was nice enough to fix https://github.com/nical/lyon/pull/595 the tesselator in the 0.15 branch, so now after a `cargo update` to update lyon, things are working as expected!
