### ISSUE TITLE
Trait for the Model

### ISSUE THREAD

**Issue by emmanuelantony2000** [nannou-org/nannou#579]
Hey the struct that we are defining, Model, can implement a trait, from the Nannou library, so that implementation and definition of the struct App can be easier.

**Comment by mitchmindtree** [comment]
Thanks for sharing your thoughts @emmanuelantony2000!

We did initially consider using a trait for the model, however decided that the current API might be a little simpler for brand new users to nannou & rust.

We aimed to avoid the barrier to entry of needing to learn how to use Rust traits, and instead provide an API based on plain-old-functions in the hope that it's a little easier to grok for newcomers from other languages and frameworks like Processing or OF.

That said, I do agree that providing a `Model` trait might be a little better if the target audience was only existing Rust developers. For example, we have a problem with the current API where its easy to forget to "register" new functions after you've written them and start wondering why they aren't getting called. This would not be a problem if all of the functions were methods on a trait.

On the other hand, the existing API gives us a little extra flexibility in other ways, like allowing the user to easily register different functions for different windows (or for all windows in the case they're passed to the app builder).

I hope this helps to clarify our decision making process a little!
