### ISSUE TITLE
app.elapsed_frames() == 1 doesn't work on my enviroment

### ISSUE THREAD

**Issue by yutannihilation** [nannou-org/nannou#586]
(Disclaimer: this is probably just because my environment is weird like #575, but let me file this in case someone sees the same issue)

The following example doesn't change the color of the window, while, strangely, it prints `Frame: 1`... I have no idea what is happening just as #575, but if I change the condition to `< 4`, it works. So, it seems multiple frames are processed at once.

``` rust
use nannou::prelude::*;

fn main() {
    nannou::sketch(view).run();
}

fn view(app: &App, frame: Frame) {
    let draw = app.draw();

    if app.elapsed_frames() == 1 {
        draw.background().color(WHITE);
        println!("Frame: {}", app.elapsed_frames());
    }

    draw.to_frame(app, &frame).unwrap();
}
```

**Comment by mitchmindtree** [comment]
Hmmm this is very strange too!

Your example seems to work as expected for me. The particularly strange thing to me is that nannou uses an intermediary frame before drawing to the swapchain window. This intermediary frame always stores what was drawn to it in the previous frame and is never cleared unless the user does so with `draw.background().color(color);` or `frame.clear(color);`. It's almost as though the draw commands we submit to the GPU are completely ignored for the first few frames on your system for some reason?

The condition `< 4` leads me to the suspicion that this has something to do with the double/triple buffer used for your swapchain. It almost seems as though the first frame for each is a "staging" frame used to prep the swapchain images before the real drawing begins. That said, this still makes no sense as to why the intermediary frame does not retain the expected colour. E.g. even if the first two or three frames are "staging" frames, the intermediary image should still contain a white image that gets drawn to the window after staging is complete anyway. :thinking:

**Comment by yutannihilation** [comment]
Thanks for taking a prompt look!

After experimenting a bit more, I think now I see what's happening here; the frame was actually drawn, but then got blown away immediately because my window manager resized the window for unknown reason... (c.f. https://github.com/nannou-org/nannou/issues/575#issuecomment-620311038 ).

So, I'm closing this as a duplicate of #575. Sorry for the noise!
