### ISSUE TITLE
distance between points

### ISSUE THREAD

**Issue by milonite** [nannou-org/nannou#588]
in p5js there's a dist function to get the distance between 2 points.
https://p5js.org/reference/#/p5/dist

There's an equivalent in nannou?
I was not able to find it in the documentation.
Even if it's a simple thing is very used in p5js projects so would make sense add it as an util

**Comment by MacTuitui** [comment]
You can do `(p1-p0).magnitude()`.

**Comment by JoshuaBatty** [comment]
you can also go `p1.distance(p0);`

**Comment by mitchmindtree** [comment]
Closing this now, though feel free to re-open if you're still unsure how to use the advice shared above.
