### ISSUE TITLE
width and height of drawn shapes seem to be half of what they should be

### ISSUE THREAD

**Issue by dominictwlee** [nannou-org/nannou#598]
v0.14

So a weird thing I noticed is that shapes are being drawn at half their size even when I explicitly declare that w and h should match window.len() and window.h() respectively.

This doesn't match up with the documentation for the coordinate system, which demonstrates the correct behaviour.
![image](https://user-images.githubusercontent.com/34794189/81555731-fabcde00-9380-11ea-92f2-d492a06a661c.png)

Please see below a minimal example:
```
use nannou::prelude::*;

fn main() {
    nannou::sketch(view).run()
}

fn view(app: &App, frame: Frame) {
    // Begin drawing
    let draw = app.draw();
    let window = app.window_rect();

    // Clear the background to blue.
    draw.background().color(WHITE);

    // Draw a rect that follows a different inverse of the ellipse.
    draw.rect()
        .xy(window.top_left())
        .w(window.len())
        .h(window.h())
        .color(BLACK);

    draw.to_frame(app, &frame).unwrap();
}
```

Which results in a halved rect.
![image](https://user-images.githubusercontent.com/34794189/81556086-a1a17a00-9381-11ea-947d-f75d5b17df0f.png)

**Comment by mitchmindtree** [comment]
Thanks for the issue @dominictwlee !

There was a DPI-related bug in the 0.14 release, but that was patched in 0.14.1 - could you try running `cargo update` to make sure you're on the latest version?

If the bug is still occurring, could you try running the window coordinates example and posting a screenshot of it here? You can run it with:

```
cargo run --release -p examples --example window_coordinates
```

**Comment by yutannihilation** [comment]
>         .xy(window.top_left())

IIUC, this sets the *center* of the rect to the top left corner. So, isn't the result expected...?

**Comment by mitchmindtree** [comment]
@yutannihilation ahh thanks for your input @yutannihilation, you're right - I clearly didn't read the example properly!

@dominictwlee could you point out the part of the guide that you feel is misleading?

**Comment by dominictwlee** [comment]
Oops my bad! For some reason I thought width and height weren't scaling properly, turns out part of the rect was just being drawn outside of the window rect.

I think the docs are fine now that I've realized that's the case.

I probably was confused because I was looking at some of the nature of code nannou examples and saw a similar implementation with top left, in which half the top rect is being rendered outside of the window rect.

https://github.com/nannou-org/nannou/blob/master/nature_of_code/chp_01_vectors/1_5_vector_magnitude.rs
