### ISSUE TITLE
m_1_3_02 in Generative Design example doesn't work

### ISSUE THREAD

**Issue by yutannihilation** [nannou-org/nannou#609]
It seems this example just displays a black window and nothing happens when I click. Is this only a problem on my environment...? (I confirmed 0.14.1 works but the current master doesn't)

https://github.com/nannou-org/nannou/blob/master/generative_design/random_and_noise/m_1_3_02.rs

Note that I needed to re-create a texture to handle window resizing, but I don't think this matters on the result.

``` rust
fn window_resized(app: &App, model: &mut Model, dim: Vector2) {
    let window = app.main_window();
    model.texture = wgpu::TextureBuilder::new()
        .size([dim.x as u32, dim.y as u32])
        .format(Frame::TEXTURE_FORMAT)
        .usage(wgpu::TextureUsage::COPY_DST | wgpu::TextureUsage::SAMPLED)
        .build(window.swap_chain_device());
}
```

**Comment by sbauer322** [comment]
m_1_3_03 seems to have the same problem with displaying only a black window.

https://github.com/nannou-org/nannou/blob/master/generative_design/random_and_noise/m_1_3_03.rs

**Comment by JoshuaBatty** [comment]
Thanks for bringing this to our attention, should be fixed on the latest master branch now.

**Comment by yutannihilation** [comment]
Confirmed, thanks!
