### ISSUE TITLE
Update Guide example to use nannou 0.14

### ISSUE THREAD

**Issue by oseph** [nannou-org/nannou#619]
The nannou depenceny version in step 3 of the [Create a Project](https://guide.nannou.cc/getting_started/create_a_project.html) example should be updated to 0.14. 

With the current 0.12 version nannou throws a compile error expecting a reference to the Frame object.

**Comment by mitchmindtree** [comment]
Thanks for the issue @oseph! Is there any chance you'd be interested in opening a PR for this?

**Comment by oseph** [comment]
Sure! [Here's the PR.](https://github.com/nannou-org/nannou/pull/620)

**Comment by mitchmindtree** [comment]
Closed via #620.
