### ISSUE TITLE
simple_audio example crashes in Windows

### ISSUE THREAD

**Issue by BennetLeff** [nannou-org/nannou#652]
The [simple_audio](https://github.com/nannou-org/nannou/blob/master/examples/audio/simple_audio.rs) example crashes on Windows 10 with the error `thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Os { code: -2147417850, kind: Other, message: "Cannot change thread mode after it is set." }'`. It seems like this is related to [this issue](https://github.com/RustAudio/cpal/pull/330) with `cpal`. Honestly, I'm not yet familiar enough with Rust to debug this one all on my own but I'd be happy to help fix it.

**Comment by BennetLeff** [comment]
I've played around with the code a bit more. The offending code is this:

```
let stream = audio_host
        .new_output_stream(model)
        .render(audio)
        .build()
        .unwrap();
```

Does anyone know what I can do to prevent it from changing the thread mode?

**Comment by lpil** [comment]
I've hit this same problem today.

**Comment by mitchmindtree** [comment]
Thanks for the report folks, I suspect this is related to #483.
