### ISSUE TITLE
Hi, I am curious to know if this is as easy as using Processing language?

### ISSUE THREAD

**Issue by Joe23232** [nannou-org/nannou#659]
Hi, I am curious to know if this is as easy as using Processing language?

**Comment by mitchmindtree** [comment]
We would love for nannou to be as accessible as Processing eventually, but we still have a long way to go. Getting into nannou at the moment still requires some extra patience, a willingness to experiment, and perhaps a desire for greater performance or low level access that is difficult to achieve in Processing. Rust is probably a little closer to OpenFrameworks than it is to Processing, if that makes sense.

Be sure to check out [the guide](https://guide.nannou.cc/) for more info on nannou.

It would likely be useful for nannou to have a chapter in the guide with comparisons to Processing and other creative coding frameworks. Would you like to open an issue for this?

**Comment by Joe23232** [comment]
> We would love for nannou to be as accessible as Processing eventually, but we still have a long way to go. Getting into nannou at the moment still requires some extra patience, a willingness to experiment, and perhaps a desire for greater performance or low level access that is difficult to achieve in Processing. Rust is probably a little closer to OpenFrameworks than it is to Processing, if that makes sense.

I see mate.

> Be sure to check out the guide for more info on nannou.

Sure mate, thanks :)

> It would likely be useful for nannou to have a chapter in the guide with comparisons to Processing and other creative coding frameworks. Would you like to open an issue for this?

Yes please :)

**Comment by anselanza** [comment]
Close issue please!
