### ISSUE TITLE
hot/live reloading or faster compile?

### ISSUE THREAD

**Issue by mlg556** [nannou-org/nannou#661]
Hi, I am a big fan of Processing and decided to give nannou a shot! so far I like it very much, but one problem I have is it takes about 10 seconds(on my old 2014 macbook air) when I change a single variable (for example x position), is there support for live reloading? or do you have any recommendations for faster compiling?

**Comment by kazimuth** [comment]
See #387.

(I've had luck applying the instructions under "enable fast compiles" [here](https://bevyengine.org/learn/book/getting-started/setup/).)

**Comment by mlg556** [comment]
thanks!
