### ISSUE TITLE
Is nannou capable of doing 3D graphics?

### ISSUE THREAD

**Issue by Joe23232** [nannou-org/nannou#678]
Is `nannou` capable of doing 3D graphics?

**Comment by MacTuitui** [comment]
Yes, but no.

nannou uses `wgpu` as its graphics backend, a wonderful project aiming at bridging modern graphics API together (well, Vulkan and Metal). nannou does also the smart thing in exposing most of its internal graphics to you so *if you want to*, you can access the rendering process and do whatever you want there. So you can render 3D stuff here, have shaders go wild and everything, but nannou will not do anything for you. You must actually know how to use `wgpu`, define your own rendering pipelines, allocate memory on the GPU, etc....  So yes, you can do 3D graphics *within* a nannou project, but nannou will not help you.

**Comment by Joe23232** [comment]
Right I see mate.
