### ISSUE TITLE
Examples build fails on nightly

### ISSUE THREAD

**Issue by grantgustafson** [nannou-org/nannou#694]
Examples depends on Audrey which fails to build tracked by [this](https://github.com/RustAudio/audrey/issues/27) issue.

**Comment by grantgustafson** [comment]
Opened a [PR](https://github.com/RustAudio/audrey/pull/28) to Audrey to fix underlying issue.

**Comment by Woyten** [comment]
With the [newest Rust release](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html) this problem has landed in the stable toolchain. Would it be possible to publish a fixed nannou_audio-0.15.1 quickly?

**Comment by mitchmindtree** [comment]
Closing as I believe these changes have landed and the issue has since been addressed. Thanks again for the PR :)
