### ISSUE TITLE
blank window for every example on Ubuntu 20.10 with Intel graphics

### ISSUE THREAD

**Issue by rjpgt** [nannou-org/nannou#698]
I am getting a blank window with a white background on running the examples after the installation of nannou. The only messages in the console are these:

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

WARNING: lavapipe is not a conformant vulkan implementation, testing use only.

Running simple_window reports all window and mouse events.
Thanks.

**Comment by rjpgt** [comment]
In addition to the blank white screen, every example I have run crashes when the window is resized a few times. I get the following message then:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AllocationError(OutOfMemory(Device))', /home/myusername/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.6/src/device/mod.rs:324:14

**Comment by DevinBayly** [comment]
I'm also experiencing this issue with slightly different output. I'd love to use nannou, but can't clear the first hurdle.
```
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
WARNING: lavapipe is not a conformant vulkan implementation, testing use only
```

**Comment by rjpgt** [comment]
The problem was solved when using the default graphics drivers. Today, after an update from ppa:oibaf/graphics-drivers my system was unusable -- the desktop was unstable. When I purged the ppa drivers and reverted to the default drivers, not only did the desktop become usable, but the examples started working. The two errors I mentioned above are no longer present.
