### ISSUE TITLE
Perlin returns zero regardless of position

### ISSUE THREAD

**Issue by zmitchell** [nannou-org/nannou#701]
I'm trying to make a flow field and visualize it by placing lines in a grid where the angle of the line is determined by the Perlin noise. This is the program I've written to do so:
```rust
use nannou::noise::{NoiseFn, Perlin};
use nannou::prelude::*;

struct Model {}

fn main() {
    nannou::app(model).simple_window(view).size(600, 600).run();
}

fn model(_app: &App) -> Model {
    Model {}
}

fn view(app: &App, _model: &Model, frame: Frame) {
    let draw = app.draw();
    let win = app.main_window();
    win.set_resizable(false);
    let length = win.rect().w() as f32;
    let grid_size = 10;
    let step_size = length / (grid_size as f32);
    let noise = Perlin::new();
    draw.background().color(THISTLE);
    for i in 0..grid_size {
        for j in 0..grid_size {
            let line_start = pt2(
                (j as f32 + 0.5) * step_size - length / 2.0,
                (i as f32 + 0.5) * step_size - length / 2.0,
            );
            let angle = noise.get([line_start.x as f64, line_start.y as f64]) as f32 * TAU;
            let line_end = polar_point(line_start, 15.0, angle);
            draw.ellipse().xy(line_start).radius(5.0).color(STEELBLUE);
            draw.line().points(line_start, line_end).color(STEELBLUE);
        }
    }
    if app.elapsed_frames() == 1 {
        win.capture_frame("vector_field.png");
    }
    draw.to_frame(app, &frame).unwrap();
}

fn polar_point(origin: Point2, r: f32, theta: f32) -> Point2 {
    pt2(r * theta.cos(), r * theta.sin()) + origin
}
```

The weird thing is that `noise.get()` returns 0 for all of the locations that I give it. I've verified this by printing out the value of `noise.get()`, but you can see it as well in the rendered image.
![vector_field](https://user-images.githubusercontent.com/10246891/104859461-8402b800-58f3-11eb-9a30-7be69eb6bb37.png)

However, if I allow the window to be resized and then resize the window, suddenly all of the lines point in different directions! 
![vector_field](https://user-images.githubusercontent.com/10246891/104859487-c75d2680-58f3-11eb-9558-f60241a5e26d.png)

I expect Perlin noise to be smoother than this, so I'm interpreting this as an error as well. I'm very new to `nannou` though, so I suspect the error is mine. Can you help me figure out what's going wrong? I've tried setting a different seed, but that didn't change anything.

**Comment by jeffreyrosenbluth** [comment]
Your points are probably too far apart for perlin noise, try:
```let k = 0.003;```
 ```let angle = noise.get([k * lline_start.x as f64, k * line_start.y as f64]) as f32 * TAU;```

**Comment by zmitchell** [comment]
Scaling the inputs fixes both issues. I'm still a little puzzled why the Perlin noise function would ever return zero for all inputs though.

**Comment by jeffreyrosenbluth** [comment]
If I recall perlin nosie is periodic and zero on the integers so my guess is your `linestart` was laning on integers.

**Comment by zmitchell** [comment]
Ah, that would explain why I suddenly see non-zero values when the window is resized (my grid points no longer lie on exact integer values). Thanks for your help!
