### ISSUE TITLE
scale_x/y/z are broken

### ISSUE THREAD

**Issue by deets** [nannou-org/nannou#705]
Hi,

while playing around with some scaling, I discovered that nothing was drawn when using scale_x/y. But global scaling worked. I then stumbled over this:

 https://docs.rs/nannou/0.15.0/src/nannou/draw/mod.rs.html#273

Using scale_geom((10.0, 1.0, 1.0)) works as advertised, but obviously if any of the arguments is 0, we are in trouble. So this should be S::one() (if that exists?).

**Comment by mitchmindtree** [comment]
Thanks for the report! Closed via #692.
