### ISSUE TITLE
Crash on Macs when running the examples

### ISSUE THREAD

**Issue by danwilhelm** [nannou-org/nannou#719]
**Workaround**
This issue has been reported several times on the Nannou Matrix chat. There is a temporary workaround:

> In `nannou/src/frame/mod.rs`, change the line `pub const DEFAULT_MSAA_SAMPLES: u32 = 4;` from 4 to 1.

---

**Problem**
Many examples (e.g. simple_window, wgpu_compute_shader) quickly crash on Macs, yielding the error `"No render pipeline state bound"`. Some example apps seem to work without a problem (e.g. wgpu_triangle), even with MSAA. These seem to (1) define their own render pipeline, and (2) do not call `frame.clear()`.

**Example**
`cargo run --example simple-window` crashes immediately with the error.

**The Workaround is not a Solution**
I am hesitant to provide the above workaround as a PR, because:
+ It would change the default behavior of existing apps; and 
+ 4x MSAA worked on versions of Nannou prior to Dec 9, 2020. It is also verified that Macs are capable of 4x MSAA via [the wpu-rs `msaa-line` example](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/msaa-line) -- indicating a bug in Nannou.

**Findings**
Here are a few results of investigating this issue:
1. The bug seems to have been a side effect of moving from wgpu 0.5 to 0.6. A working commit is [here](https://github.com/nannou-org/nannou/tree/2cedce1014053c9771e592f8841d24006a05d9b2). Here is [the first non-working commit](https://github.com/nannou-org/nannou/tree/f2744d389b3b3708ee3071cf1fc2400b95a46f0d).
2. I believe the issue is caused by the render pass in [`resolve_texture`](https://github.com/nannou-org/nannou/blob/master/nannou/src/wgpu/mod.rs#L130). The examples work if this render pass is removed. 
3. I hypothesize that placing this render pass in a pipeline may resolve the issue -- perhaps move it into `Reshaper` as it originally was. (The Metal documentation seems to indicate vaguely that a render pipeline may be needed to perform MSAA.) 
4. The only two render functions that are not in pipelines are `clear_texture` and `resolve_texture`, both in `nannou/src/wpu/mod.rs` -- and both can cause crashes. (`clear_texture` causes a crash in examples that run `frame.clear()` -- even if they use a custom render pipeline.)

**Notes**
+ This [msaa-line PR](https://github.com/gfx-rs/wgpu-rs/pull/688) explains that MSAA values of 1 and 4 are the only universally accepted values. Further, there is currently no way in WebGPU to query the supported values.

**Comment by danwilhelm** [comment]
Related: https://github.com/nannou-org/nannou/issues/599

**Comment by mitchmindtree** [comment]
Thanks for diving into this @danwilhelm!

> The Metal documentation seems to indicate vaguely that a render pipeline may be needed to perform MSAA.

Ahh interesting, do you happen to remember where you read this or have a link?

If I understand this correctly, the theory is that any render pass command that performs an MSAA resolve *without* having specified a pipeline will crash like this on Metal? I wonder why this is now the case as of 0.6 but did not appear to be an issue on 0.5...

I just asked on the wgpu matrix chat, and apparently:

> it's totally fine to have a pass without a pipeline, in Metal as well

I do remember checking this with them a long time ago too, so there might be something else going on. Though I'd still be interested to read the relevant section in those Metal docs if you can find them again.

I wonder then if perhaps it was some other change between 0.5 and 0.6 that we did not do correctly. E.g. perhaps a texture format was changed or something along these lines. If it appears that removing this render pass fixes the crash, then perhaps one of our assumptions for the pass has been broken (e.g. maybe either the dimensions or texture format differs between src and dst textures).

Unfortunately I don't have a macOS machine on me for testing this. Is there any output provided when the crash occurs that you could share? Alternatively, perhaps there is an environment variable or something that we can set to get more information from Metal about the crash?

I believe error reporting was improved quite a bit in wgpu 0.7, though some work is required to get there. I've had a couple of failed attempts at updating conrod_wgpu to 0.7 so that we can update nannou, but I'll open a separate issue for this.

**Comment by JoshuaBatty** [comment]
Can confirm the examples mentioned above are also crashing on my mac machine. I've included a snippet of the crash report below. 

```
Process:               simple_window [1714]
Path:                  /Users/USER/Documents/*/simple_window
Identifier:            simple_window
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [1018]
Responsible:           Electron [802]
User ID:               502

Date/Time:             2021-04-15 16:06:04.278 +0200
OS Version:            Mac OS X 10.14.6 (18G2022)
Report Version:        12
Bridge OS Version:     3.0 (14Y906)
Anonymous UUID:        EDA4AA72-35F2-572E-CCC3-9F2E0B099EDB


Time Awake Since Boot: 2300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 0000000107914000-0000000107dd5000 [ 4868K] r-x/r-x SM=COW  /Users/USER/Documents/*

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.AMDMTLBronzeDriver  	0x00007fff255b87b8 amdMtlBronzeResourceMgrValidateConstantState(BronzeCmdBufInfoRec*, BronzeRsrcMgrRec*, BronzeRsrcMgrConstStateRec const*) + 28
1   com.apple.AMDMTLBronzeDriver  	0x00007fff255bf7ac amdMtlBronze_VI_DrawAutoIndexPrims(BronzeRenderCmdEncoderMembersRec*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) + 78
2   com.apple.AMDMTLBronzeDriver  	0x00007fff255bbcbf -[BronzeMtlRenderCmdEncoder drawPrimitives:vertexStart:vertexCount:] + 61
3   simple_window                 	0x0000000107b24ff5 _$LT$gfx_backend_metal..command..CommandBuffer$u20$as$u20$gfx_hal..command..CommandBuffer$LT$gfx_backend_metal..Backend$GT$$GT$::draw::hf0863386dea470a1 + 197
4   simple_window                 	0x0000000107a4709f wgpu_core::command::render::_$LT$impl$u20$wgpu_core..hub..Global$LT$G$GT$$GT$::command_encoder_run_render_pass_impl::h71bbe764c4e50fc2 (.llvm.9697927731641586673) + 12319
5   simple_window                 	0x0000000107acb3a3 _$LT$wgpu..backend..direct..Context$u20$as$u20$wgpu..Context$GT$::command_encoder_end_render_pass::h1ea730ed1625717c + 131
6   simple_window                 	0x00000001079aa1ce nannou::wgpu::texture::reshaper::Reshaper::encode_render_pass::h9694a23e4f4ee5db + 766
7   simple_window                 	0x00000001079b0d66 nannou::frame::Frame::submit_inner::he8873cab38db3f21 + 614
8   simple_window                 	0x000000010794251f simple_window::view::h02fbfdba957e8910 + 31
9   simple_window                 	0x0000000107928eb3 nannou::app::run_loop::_$u7b$$u7b$closure$u7d$$u7d$::heb3f7744f70522fa + 1587
10  simple_window                 	0x000000010792750b _$LT$winit..platform_impl..platform..app_state..EventLoopHandler$LT$T$GT$$u20$as$u20$winit..platform_impl..platform..app_state..EventHandler$GT$::handle_nonuser_event::hdb6711c3f2bcdc16 + 155
11  simple_window                 	0x0000000107a10139 winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::h25630c7720670675 + 825
12  simple_window                 	0x0000000107a11d01 winit::platform_impl::platform::app_state::AppState::cleared::h5708ec90119dc391 + 1489
13  com.apple.CoreFoundation      	0x00007fff30b736d8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
14  com.apple.CoreFoundation      	0x00007fff30b7360d __CFRunLoopDoObservers + 451
15  com.apple.CoreFoundation      	0x00007fff30b15e57 __CFRunLoopRun + 1431
16  com.apple.CoreFoundation      	0x00007fff30b1566e CFRunLoopRunSpecific + 455
17  com.apple.HIToolbox           	0x00007fff2fd741ab RunCurrentEventLoopInMode + 292
18  com.apple.HIToolbox           	0x00007fff2fd73ee5 ReceiveNextEventCommon + 603
19  com.apple.HIToolbox           	0x00007fff2fd73c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
20  com.apple.AppKit              	0x00007fff2e10b77d _DPSNextEvent + 1135
21  com.apple.AppKit              	0x00007fff2e10a46b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
22  com.apple.AppKit              	0x00007fff2e104588 -[NSApplication run] + 699
23  simple_window                 	0x00000001079259ab winit::platform_impl::platform::event_loop::EventLoop$LT$T$GT$::run::h1b9683599b14b277 + 299
24  simple_window                 	0x000000010794ba4e winit::event_loop::EventLoop$LT$T$GT$::run::h0144416054a9aaca + 62
25  simple_window                 	0x000000010794c0a3 nannou::app::Builder$LT$M$C$E$GT$::run::h5c54d7dbef65226a + 1027
26  simple_window                 	0x000000010794227d simple_window::main::h62ce290a572a3811 + 93
27  simple_window                 	0x000000010791baaa std::sys_common::backtrace::__rust_begin_short_backtrace::h910a7d6b3268ef18 + 10
28  simple_window                 	0x000000010791bacc std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h2243d140d91f36ad (.llvm.6940286201204460204) + 12
29  simple_window                 	0x0000000107d0da34 std::rt::lang_start_internal::h1faf79574185df6d + 644
30  simple_window                 	0x00000001079425c9 main + 41
31  libdyld.dylib                 	0x00007fff5ca9f3d5 start + 1
```
