### ISSUE TITLE
link is stale

### ISSUE THREAD

**Issue by macginitie** [nannou-org/nannou#765]
on the page at https://guide.nannou.cc/getting_started/platform-specific_setup.html, the link to the repo goes to the older, readonly version.

**Comment by mitchmindtree** [comment]
Thanks for the issue! Any chance you would be interested in opening a PR to fix this?

**Comment by macginitie** [comment]
I can try, sure

**Comment by macginitie** [comment]
https://github.com/nannou-org/nannou/pull/767

**Comment by mitchmindtree** [comment]
Closed via #767.
