### ISSUE TITLE
LoopMode::Wait not working on macOS

### ISSUE THREAD

**Issue by zgotsch** [nannou-org/nannou#781]
Nannou version: `0.17.1`
macOS version: Big Sur (11.4)

After I `app.set_loop_mode(LoopMode::wait());`, I expect my view function to be called only on input events. However, it seems to be called for each frame at 60fps.

Is this working on other platforms? I am happy to take a crack at working on this but I might need some guidance.

Here are some events that are flowing through the `winit` event loop:
```
...
NewEvents(WaitCancelled { start: Instant { t: 1006573215416347 }, requested_resume: None })
MainEventsCleared
RedrawRequested(WindowId(Id(140410039122816)))
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { t: 1006573258088858 }, requested_resume: None })
MainEventsCleared
RedrawRequested(WindowId(Id(140410039122816)))
RedrawEventsCleared
...
```

Taking a quick look at `app.rs`, it seems like `MainEventsCleared` always results in an invocation of the user's view function, unless using `LoopMode::NTimes` where all number of renders has exceeded "n". I am still having trouble understanding how the loop "knows" to render at 60fps, or put another way, why the `winit` `ControlFlow::Wait` is being interrupted.

**Comment by zgotsch** [comment]
I have verified that `LoopMode::Wait` works as expected on Windows 11.

**Comment by gmunk** [comment]
Hello @zgotsch,

I'm also on Big Sur (11.3.1), I plan to update to 11.5.1 and I'll test with it to try and replicate the issue, anyways I can confirm what you are saying. `LoopMode::Wait` is not behaving as expected for me too. 

However I'd like to direct attention to the fact that when one sets the App's loop mode to `LoopMode::NTimes` there aren't any issues with interuptions from winit. I think it's worth its while to consider this when trying to find the actual cause for this issue.

**Comment by zgotsch** [comment]
Unfortunately, there's not been any feedback from `winit` maintainers on https://github.com/rust-windowing/winit/issues/1985. For my own use, I have been using the fix in https://github.com/nannou-org/nannou/pull/782 backported onto `0.17.1`.

`LoopMode::NTimes` works because `apply_update` is not called when the loop count exceeds the specified number of updates. My fix applies this same behavior when no events have been received between `NewEvents` and `MainEventsCleared`.
