### ISSUE TITLE
Add in no_loop_mode() into the Loop Mode enum

### ISSUE THREAD

**Issue by JoshuaBatty** [nannou-org/nannou#81]
calling no_loop_mode() should still allow the view() function to run once. 

The contents that were drawn into the frame should remain visible and unchanged until loop mode is triggered again.

**Comment by mitchmindtree** [comment]
Currently there are two modes:

1. `LoopMode::Rate` (updates and draws at some consistent rate).
2. `LoopMode::Wait` (updates and draws when new user input is received).

This should be added as a third variant, something like:

3. `LoopMode::Once` (update and view are called only *once*. `event` is still called with user input events though).

The API might look something like this:

```rust
// In the `model` function.
app.loop_once();
```

A user could also manually trigger another loop via calling `app.loop_once()` in response to some user event (e.g. `KeyPressed`, etc).

**Comment by mitchmindtree** [comment]
Alternatively the variant could be something like:

3. `LoopMode::NTimes(usize, rate)` where the usize indicates the number of times that the `update -> view` loop will be run and rate specifies the time interval. This might be a bit more flexible than a `Once` variant, as `Once` could be expressed via `NTimes(1, _)`.

`app.loop_once();` would set the loop mode as `LoopMode::NTimes(1, _)`.

**Comment by CGUTA** [comment]
If it is ok with everybody I am going to give it ago this afternoon.

**Comment by mitchmindtree** [comment]
Sounds good! I will be happy to review. Let me know if you need help navigating the application loop code, it can be a little tricky to follow as there are a lot of invariants imposed by the vulkan swapchain! I'll try to point you in the right direction if I'm around :)

**Comment by mitchmindtree** [comment]
This has since been implemented in #353 - closing.
