### ISSUE TITLE
`capture_frame` not working with `loop_once`?

### ISSUE THREAD

**Issue by mr-systems** [nannou-org/nannou#830]
Recently I've been struggling with trying to save the current frame as an image (or, more generally, rendering to an image rather than a window); I normally do single-frame work (i.e. `LoopMode::loop_once()`), and `capture_frame` seems like it should be the answer to all my problems, but it doesn't work with `loop_once()`. Is this a bug or a misunderstanding on my part?

(code I was using to test this:)
```rs
extern crate nannou;
use nannou::prelude::*;

fn main() {
    nannou::app(model)
        .loop_mode(LoopMode::loop_once())
        .simple_window(view)
        .run();
}

fn model(_app: &App) -> () {}

fn view(app: &App, _model: &(), frame: Frame) {
    app.main_window().capture_frame("try_capture.png");
    let draw = app.draw();
    draw.background().color(rgb8(0xff, 0x00, 0x00));
    draw.to_frame(app, &frame).unwrap();
}
```
Observed behaviour: `try_capture.png` was not created.
Built using nannou 0.18.1 on nightly.

**Comment by sidwellr** [comment]
That code worked as expected for me. The file `try_capture.png` was created as expected. I'm using stable, not nightly, but I don't think that would cause the issue. Perhaps the file is created in a different place from what you expect. If you are using a workspace, the file will be created in the workspace directory, not the project directory.

**Comment by mr-systems** [comment]
I opened a blank project with `cargo new`, stuck that in as the main.rs, and didn't get anything.
I changed the `loop_once()` to `wait()` and it actually gave me a `try_capture.png` (all red pixels, as expected), so I know the file wasn't being made in the wrong place, it just seems to be something about `loop_once()`.

OS is macOS 11.5.2, if that matters.

**Comment by sidwellr** [comment]
Perhaps the OS does matter; I use Windows 10. You might try `loop_ntimes(2)` to see if looping twice works.

**Comment by Woyten** [comment]
It could be the problem reported in #826. Could you check if the branch `publish-nannou-0.18.1` has the same problem?

**Comment by mr-systems** [comment]
@Woyten That branch does indeed have the same issue.
Tested with
```toml
nannou = { git = "https://github.com/nannou-org/nannou.git", branch = "publish-nannou-0.18.1" }
```

**Comment by mr-systems** [comment]
@sidwellr I also tried `loop_ntimes(2)`, which got me a 0-byte `try_capture.png`:
```
> ls -GFag
...
-rw-r--r--@ 1 staff     0B Jan  4 00:51 try_capture.png
...
```

**Comment by maurimura** [comment]
@mr-systems I have it working with `loop_once` mode. The frame was captured after I closed the window but it won't work if you kill the process on the terminal.

According to this, it should be called after a `submit` event or a drop one.
https://github.com/nannou-org/nannou/blob/642019d38a8234bdc67212d62e96968e21fe3b0b/nannou/src/window.rs#L1481-L1492

And the `submit` event is called on a Frame drop.
https://github.com/nannou-org/nannou/blob/642019d38a8234bdc67212d62e96968e21fe3b0b/nannou/src/frame/mod.rs#L254-L270

So maybe you can call the `submit` event by yourself, but this will be done automatically if the program is closed properly.

**Comment by mr-systems** [comment]
Thank you, that finally connected the dots! Seems like I was looking for everything in the wrong direction. It'd be nice if this information was a little more prominent though.

Also, not sure if this is intended behaviour but quitting (via Command-Q) seems to act the same way as killing the process in terminal, when I would expect it to work more like closing the window.

**Comment by maurimura** [comment]
@mr-systems I'm not an Apple expert, but I think closing the window using command-W should trigger the drop on your program.
