### ISSUE TITLE
add in a color method for defining single value gray scale colors

### ISSUE THREAD

**Issue by JoshuaBatty** [nannou-org/nannou#84]
instead of typing out .rgb(0.5,0.5,0.5); it would be nice to have something like .gray(0.5)

**Comment by mitchmindtree** [comment]
If anyone is interested, this might make for a good first issue!

See the steps I've outlined [here](https://github.com/nannou-org/nannou/issues/180#issuecomment-522250991) - something very similar could be applied to add support for this.
