### ISSUE TITLE
Update model from view function

### ISSUE THREAD

**Issue by tqwewe** [nannou-org/nannou#841]
I have a case where I need to update the model from the `view` function, but I don't have access to `&mut Model`.

In my case, I'm looping over pixels of image data and draw a ellipse for each pixel, but I also calculate the brightest pixel from the loop, and I'd like to update my model with the previous frame brightest pixel.

If I do it in update separately, it means I'd have to perform the same computation twice when it can easily be done once in the view function.

**Comment by sidwellr** [comment]
Add a private `Draw` instance to your model, like `draw: Draw`. Create it in the `model` function with "draw: Draw::new()". Then do your looping in the `update` function and use`model.draw` for drawing. The `view` function then just has one line: `model.draw.to_frame(app, &frame).unwrap();` to render your drawing to the frame.

This bends the Model-Update-View pattern almost beyond recognition! But it should work...

**Comment by tqwewe** [comment]
Sounds like a great solution! I think that works great for my use case thank you
