### ISSUE TITLE
Nannou is slow compared to p5.js

### ISSUE THREAD

**Issue by Enforcer007** [nannou-org/nannou#866]
I'm trying out examples from generative_design folder and it seems that nannou is very slow compared to the p5.js implementation. Sharing the quality of renderings below:

Nannou:

https://user-images.githubusercontent.com/6951100/172839177-1bf2f062-6407-425a-80d1-2fee2aa33832.mp4

P5js:

https://user-images.githubusercontent.com/6951100/172839212-17678fce-9c1b-43ab-aa5c-9772842f396b.mp4

I thought frameworks built on Rust are faster. But this seems quite opposite.

Nannou-Code: https://github.com/nannou-org/nannou/blob/master/generative_design/image/p_4_3_1_01.rs
P5js Code: https://editor.p5js.org/generative-design/sketches/rknNg99c614

My System Config:
Ubuntu: v20.04
Nannou: v0.18

**Comment by JoshuaBatty** [comment]
Please make sure you are running nannou in release mode, otherwise you will notice slow performance. 

`cargo run --release --example p_4_3_1_01`
