### ISSUE TITLE
Background Colors are Incorrect

### ISSUE THREAD

**Issue by Enforcer007** [nannou-org/nannou#868]
If r,g,b color values are non-zero then the background color is always white:

`draw.background().rgb(217.0, 24.0, 214.0);` shows white background  ⚪, expected violet  🟣
`draw.background().rgb(35.0, 217.0, 15.0);` shows white background ⚪, expected yellow  🟡

Represents different background color when atleast one value is zero:
`draw.background().rgb(35.0, 0.0, 15.0);` shows pink  💗, expected dark brown  🟤
`draw.background().rgb(35.0, 150.0, 0.0);` shows yellow  🌕, expected green  🟢

Below is the code:
```rust
use nannou::prelude::*;

fn main() {
    nannou::sketch(view).run();
}

fn view(app: &App, frame: Frame) {
    // get canvas to draw on
    let draw = app.draw();

    // set background to blue
    draw.background().rgb(35.0, 150.0, 0.0);

    // put everything on the frame
    draw.to_frame(app, &frame).unwrap();
}

```
Nannou version: 0.18.1
OS: Ubuntu 20.04

**Comment by JoshuaBatty** [comment]
Nannou colour values are between 0.0 and 1.0, not the usual 0 - 255.

**Comment by Enforcer007** [comment]
What's the advantage of using [0,1] than the standard range i.e, [0,255]

hsl also follows same principle rather than [0,360] it's [0,1]

**Comment by JoshuaBatty** [comment]
Mainly, only 255 unique values can be represented when each channel's colour value is a byte. Floating point numbers over a far greater resolution so more colors can be accessed. 

Nannou does have an `rgb8` function that lets you specify colours in ranges between 0,255 if you would prefer though. [](https://docs.rs/nannou/latest/nannou/color/fn.rgb8.html)
