### ISSUE TITLE
Use newer wgpu/wgsl version

### ISSUE THREAD

**Issue by jembishop** [nannou-org/nannou#925]
Seems like an old version of wgpu and wgsl shader version is being used. 
Is it worth to update? 
I would like to a compute shader with nannou,  but there is an unresolvable clash if I use 
2 wgpu versions it looks like. 

Also the out of date wgpu makes the examples and docs for using wgpu and nannou out of sync and a
bit confusing. 

I would be willing to contribute if help is needed.
Thanks.

**Comment by tychedelia** [comment]
Hi!

You may have seen our plans to replace Nannou's backend with Bevy: #953. This will keep us up to date on wgpu as well as provide more sophisticated tools for building things like compute shaders!
