### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ghost** [nannou-org/nannou#934]
I cloned the repo freshly and tried to run examples and get a segmentation fault for every example i tried to run.
![image](https://github.com/nannou-org/nannou/assets/116255686/59dcd177-cec5-43d1-868d-c797f083bed2)

**Comment by davehorner** [comment]
I just tried running a few samples this evening.
```
  Compiling examples v0.1.0 (C:\working\rust\nannou\nannou\examples)
    Finished dev [unoptimized + debuginfo] target(s) in 19.36s
warning: the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target\debug\examples\simple_ui.exe`
error: process didn't exit successfully: `target\debug\examples\simple_ui.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
not sure what to do from there.

**Comment by davehorner** [comment]
Both samples worked perfectly fine on another win64 machine.  Still not sure what's up with the configuration on my other machine, but I can play now.  thanks.
