### ISSUE TITLE
egui_extras image loader not working

### ISSUE THREAD

**Issue by danielnehrig** [nannou-org/nannou#965]
it seems like `ui.image` is unusable because it needs the loaders from egui_extras which can not be setup because of how the crate is wrapping egui which will lead to type clashes

```rust
    let egui = Egui::from_window(&window);
    egui_extras::install_image_loaders(egui.ctx());
```
will not work

**Comment by tychedelia** [comment]
> which will lead to type clashes

This makes me think that you might be including the wrong version of Egui. Our latest release uses `egui = "0.23"`

**Comment by danielnehrig** [comment]
you're right thanks for the repsonse.
on another note i had to walk away from the project because i need transparency and other WS_EX flags on my windows which does not work on win11 with nannou (blame winit i guess)
