### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#99]
- [x] Purchase the domain name.
- [x] Sort out hosting.
- [x] Transfer domain name.
- Create front end:
    - [ ] Quick summary - Discription, Vision, Features.
    - [ ] Projects (LATTICE, ORACLE, Beyond Perception, Jen).
    - [ ] Code Examples (side-by-side w/ processing).
    - [ ] Github link.

Requirements

- Nice landing page
- Forum (discourse?)
- Blog for announcements, progress, events, etc.

**Comment by JoshuaBatty** [comment]
Yes lets at least get this part going asap and then we can work out how to have a discourse forum link to it.

**Comment by tpltnt** [comment]
How is this going forward?

**Comment by JoshuaBatty** [comment]
Hi @tpltnt I just launched the redesign the of the website [here](https://nannou.cc) 

I'm going to close this issue and if there is any issues people come across feel free to create an issue on the [website repo](https://github.com/nannou-org/website).
